### ISSUE TITLE
goimagehash.PerceptionHash vs this python imagehash.phash

### ISSUE THREAD

**Issue by dancrew32** [JohannesBuchner/imagehash#102]
Comparing this python phash function:
https://github.com/JohannesBuchner/imagehash/blob/master/imagehash/__init__.py#L152-L171

To this golang phash function:
https://github.com/corona10/goimagehash/blob/master/hashcompute.go#L64-L85

There are unfortunately small deltas between the two hashing algorithms (hamming distance 0, 2, 4), so there must be a few minor deltas:

* I see the golang implementation is using bilinear and can be updated to Lanczos2 or Lanczos3 to be more similar to PIL ANTIALIAS (Lanczos).
* I also see that imagehash has the image resized to 32x32 by default where the golang is 64x64 by default.

Kind of nerdy problem, but I'd love help discovering the deltas between these two implementations. Thanks in advance.

**Comment by dancrew32** [comment]
I see ANTIALIAS is Lanczos3:
https://github.com/python-pillow/Pillow/blob/c82d2629d74b8cf67aa40f5ad8e1b93626c61ac5/src/libImaging/Resample.c#L64-L70

**Comment by corona10** [comment]
@dancrew32 Wow good catch, Can you submit the PR for this?

**Comment by corona10** [comment]
@dancrew32 Good catch, Can you please submit the patch for goimagehash?

**Comment by dancrew32** [comment]
Hey @corona10! Awesome that you saw this. I’ll try to get a PR up soon. There are still some mysterious deltas that I’ll try to setup test cases for in a branch. Comparing the numpy function internals to the nice, legible go code you’ve written has been a challenge.

**Comment by JohannesBuchner** [comment]
Please reopen if there is still an issue.

**Comment by vpatel9202** [comment]
As of today, this is still an issue. I'm getting a hamming distance of 8 running the same file through both.
