### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ezequias** [JohannesBuchner/imagehash#103]
I tried this code below with this two images and it does not work for me. Does anyone can tell me what could be done to solve this issue?

```from PIL import Image
import imagehash

hash0 = imagehash.average_hash(Image.open('bk1.jpg')) 
hash1 = imagehash.average_hash(Image.open('bk3.jpg')) 

print(hash0)
print(hash1)

print(hash0 - hash1)

cutoff = hash0 - hash1

print(hash0 == hash1)

if hash0 - hash1 < cutoff:
  print('images are similar')
else:
  print('images are not similar')
```

![bk1](https://user-images.githubusercontent.com/539561/74237630-c0c13a80-4cb2-11ea-8359-602c5817f143.jpg)
![bk3](https://user-images.githubusercontent.com/539561/74237633-c159d100-4cb2-11ea-9010-e7746285cb2d.jpg)

**Comment by JohannesBuchner** [comment]
Yes, if you give information what you expected and what the actual outcome is.

**Comment by ezequias** [comment]
@JohannesBuchner I downsize both images to 36x36px and set the cutoff to 16 and it works.

How do I figure out the correct cutoff? What this parameter really means?

**Comment by ezequias** [comment]
When it says the difference is 29 it means the matrix 8x8(64px) there are 9 totally different pixels?

**Comment by JohannesBuchner** [comment]
`hash0 - hash1` returns the number of pixels in the hash matrix that are different.

cutoff is subjective, and depends on your application and is subjective. I suppose you will need to calibrate it to some performance measures you want to achieve, or choose cutoff=1 for maximum purity.

**Comment by JohannesBuchner** [comment]
If you still have issues, please reopen.

**Comment by JohannesBuchner** [comment]
Here is some more information on how to calibrate a cutoff based on your desired false positive rates and transforms: https://tech.okcupid.com/evaluating-perceptual-image-hashes-okcupid/
