### ISSUE TITLE
[Question] Why use ITU-R 601-2 for grayscaling?

### ISSUE THREAD

**Issue by m0rtalis** [JohannesBuchner/imagehash#104]
Hi all,
is there any particular reason to use the ITU-R 601-2 transform to convert an image to grayscale?
I'm currently writing on my master thesis and noticed that most perceptual hashing algorithm use either that or the ITU-R 709 to convert images instead of other methods. I couldn't find any reason behind this and Kanan et. al. suggests in "https://doi.org/10.1371/journal.pone.0029740" that other methods might be better suited.

So is there any particular reason for it or was it just convenience?

**Comment by JohannesBuchner** [comment]
As far as I can tell, all of these methods are heuristics and somewhat arbitrarily chosen.

**Comment by m0rtalis** [comment]
Yes that's probably true. But was the conversion to grayscale here with `image.convert("L").resize((hash_size, hash_size), Image.ANTIALIAS)` also chosen arbitrarily or did you have a particular reason for it?

**Comment by JohannesBuchner** [comment]
I am unfamiliar with the IDs you mention. How would the other one be implemented in pillow? I think the answer is "it seems to work sufficiently and the other choices seem more critical".

**Comment by m0rtalis** [comment]
Ok thank you. I guess that was the answer I was looking for.
Was just wondering if there was some reasoning behind it I just don't know but I guess not :)
Thanks for your time
