### ISSUE TITLE
Bug in average_hash algorithm flips all bits, making similar pictures very dissimilar

### ISSUE THREAD

**Issue by adamryczkowski** [JohannesBuchner/imagehash#106]
```python
import imagehash
import io
from PIL import Image


file1='h_l.png'
file2='h_m.png'

with open(file1, "rb") as fh:
    png1=fh.read()

with open(file2, "rb") as fh:
    png2=fh.read()

img1 = Image.open(io.BytesIO(png1))
img2 = Image.open(io.BytesIO(png2))

hash1=imagehash.average_hash(img1, 16)
hash2=imagehash.average_hash(img2, 16)

print("Hash1: " + str(hash1))
print("Hash2: " + str(hash2))
```
Outputs
```
Hash1: fdfffffffffffc3ff81ff81ffc1ffb3ffb3ffcbfffffffffffffffffffffffff
Hash2: 01000000018000000000000000000b000b0004e007e000000000000000000000

```

![h_l](https://user-images.githubusercontent.com/4469707/78990215-2f493a00-7b36-11ea-9359-ab0d91f5489f.png)

![h_m](https://user-images.githubusercontent.com/4469707/78990220-2fe1d080-7b36-11ea-8197-6111d0e12fad.png)

This issue might be related to #103

**Comment by JohannesBuchner** [comment]
It seems like in this case, the mean pixel darkness is in one case slightly above, and in the other case slightly below the majority color. Perhaps a average hash that uses the median could perform better?

**Comment by adamryczkowski** [comment]
That fixed the problem. Thank you. I believe no pull request is necesary, as my use case is different than the use case of majority of imagehash' audience. 

Let me know, if you want me to contribute to the documentation tough.

**Comment by JohannesBuchner** [comment]
Great! Pull requests for any documentation are always welcome :)
