### ISSUE TITLE
Finding similar images after crop & scale

### ISSUE THREAD

**Issue by samgermain** [JohannesBuchner/imagehash#107]
So I'm trying to find better quality images from a set of lower quality cropped images. I was able to use imagehash to compare images of varying qualities but it didn't working for finding a full image from a cropped image.

Is there a way to find full images from cropped duplicate images? Is there any option like increasing processing time for more accurate results?

[Here's how I made use of image hash](https://github.com/samgermain/Copy_Duplicate_Images) 

Here's an example of two images which I would like to show as duplicates

-----------------------------------------------

**Here's a more in depth explanation of the problem I am trying to solve**

I have a bunch of poor quality photos that I extracted from a pdf. Somebody I know has the good quality photo's somewhere on her computer(Mac), but it's my understanding that it will be difficult to find them.

I would like to

- loop through each poor quality photo
- perform a reverse image search using each poor quality photo as the query image and using this persons computer as the database to search for the higher quality images
- and create a copy of each high quality image in one destination folder.

Example pseudocode

```
for each image in poorQualityImages:
    search ./macComputer for a higherQualityImage of image
    copy higherQualityImage to ./higherQualityImages
```

**Comment by JohannesBuchner** [comment]
Cropped images are a bit difficult, because it is really a different image then.

If the cropping is just removing borders of a fixed color, you could try to apply this to the (full) images automatically before handing them to imagehash.

If your cropped images are a small part of the full image, I think the general solution is to apply a convolution and test how good the best correlation is. This is going to be very computationally expensive, so you probably want to downscale both the full and the cropped image (and work in grayscale).

**Comment by JohannesBuchner** [comment]
You can also have a look at the colorhash I recently added for identifying potential candidates. It's not going to be very accurate, but may help with ranking.

**Comment by samgermain** [comment]
> apply a convolution and test how good the best correlation is. 

How would I do that exactly? Code wise?

Here's an example of 2 of the duplicate images by the way https://imgur.com/a/dOs0567 . With the query image being cropped

**Comment by JohannesBuchner** [comment]
I would try with scipy.signal.fftconvolve, pass the grayscale pixel values of the full image, of the cropped image, and mode='valid'.

This should return something almost like an image, which tells you the correlation at each offset.

Here is a untested sketch of code:
```
from PIL import Image
import numpy
import scipy.signal

fullimage = Image(full_filename)
croppedimage = Image(cropped_filename)

fullpixels = numpy.asarray(fullimage.convert("L"))
croppedpixels = numpy.asarray(croppedimage.convert("L"))

convolution = scipy.signal.fftconvolve(fullpixels, croppedpixels, mode='valid')
print(convolution)
print('quality of agreement:', convolution.max())
```

**Comment by JohannesBuchner** [comment]
If the two images are also rescaled additional to being cropped, the above will not work so well.

**Comment by samgermain** [comment]
@JohannesBuchner Yeah it is scaled and cropped

**Comment by JohannesBuchner** [comment]
There is crop_resistant_hashref now, which I think addresses this. If still an issue, please reopen.
