### ISSUE TITLE
Colorhash hashes don't differ with subtle changes in color

### ISSUE THREAD

**Issue by david-russo** [JohannesBuchner/imagehash#109]
Below are two files which should result in different hashes, but don't with v4.1.0:

* [imagehash.png](https://github.com/JohannesBuchner/imagehash/blob/0687d8b1ea8327fb6134fcb79eeabfb31c845b86/tests/data/imagehash.png)
* [imagehash-with-different-colors.png](https://user-images.githubusercontent.com/757021/84146763-1ab0f180-aa54-11ea-88dd-de3455fb95ed.png)

Both result in "07007000000".

**Comment by JohannesBuchner** [comment]
This is expected. Hashes are lossy.

Conversely, you could probably construct images with a certain color where very tiny color changes completely changes the hash.

**Comment by JohannesBuchner** [comment]
If you want to want finer color hashing, you can increase the colorhash binbits parameter.

**Comment by david-russo** [comment]
Thanks Johannes, that certainly cleared it up for me. I might have a go at documenting that in the README. Is there perhaps a correlation between `binbits` and hash size we could use to make colorhash's calling parameters more consistent with the other methods (by changing `binbits` to `hash_size`)?

**Comment by JohannesBuchner** [comment]
colorhashes are boolean arrays of shape (6, binbits), while the others are shaped (hash_size, hash_size).

Unfortunately this also makes it nontrivial to use the same function for converting between strings and boolean arrays.
