### ISSUE TITLE
Function hex_to_hash not work for colorhash hex's

### ISSUE THREAD

**Issue by gil9red** [JohannesBuchner/imagehash#112]
**__version__ = "4.1.0"**

Example:
```
from PIL import Image
import imagehash

img = Image.open(r'D:\foo.jpg')
hash_value = imagehash.colorhash(img)
print(hash_value)
# 03e01040000

hash_value = imagehash.hex_to_hash('03e01040000')
print(hash_value)
```

Error:
```
Traceback (most recent call last):
  File "...", line 24, in <module>
    print(hash_value)
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\imagehash.py", line 92, in __str__
    return _binary_array_to_hex(self.hash.flatten())
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\imagehash.py", line 81, in _binary_array_to_hex
    return '{:0>{width}x}'.format(int(bit_string, 2), width=width)
ValueError: invalid literal for int() with base 2: '[True, True, True, True, True, False][False, False, False, False, False, False][False, True, False, False, False, False][False, True, False, False, False, False][False, False, False, False, False, Fa
```

**foo.jpg**: https://user-images.githubusercontent.com/6244078/84967633-e0b7ad80-b12d-11ea-878d-a0fe39480b3e.jpg

**Comment by EhsanKia** [comment]
+1. just ran into a similar issue.
My hashes start as shape = (14, 3), then I convert to str() and back and I get (7,), and then compare fails.

**Comment by JohannesBuchner** [comment]
hex_to_hash cannot be used with color hashes, you have to use hex_to_flathash instead.

**Comment by EhsanKia** [comment]
I see, the documentation may need to be updated, since
>  or onedimensional arrays with dimensions binbits * 14.
sort of implies that it should handle the (14, 3) colorhash.

hex_to_flathash does load it correctly, but that's still a (1, 42) array that needs to be reshaped into (14, 3)
```
chash = imagehash.hex_to_flashhash(hash_str)
chash.hash = chash.hash.reshape(14, 3)
```

Would it be doable to have maybe a `hex_to_colorhash` function that automatically detects the bincount and loads the hex into the right shaped colorhash?

**Comment by JohannesBuchner** [comment]
Yes, I was playing with making a single function that can handle both, but concluded it cannot be generalised because the two hash types have different structures. For comparison of hashes, the shape is unimportant anyhow, as only the flattened array is compared.
