### ISSUE TITLE
Same Wavelet Hash for two different images.

### ISSUE THREAD

**Issue by Hyperclaw79** [JohannesBuchner/imagehash#114]
So far, the library is excellent in terms of both performance and accuracy. This is a very rare edge case but it exists either way, so I want to point it out.
The images used are [Piloswine](https://cdn.discordapp.com/attachments/720182069476589681/728599229781639318/pokemon.png) and [Dugtrio](https://media.discordapp.net/attachments/720182069476589681/726352591486844938/pokemon.png) sprite assets.
Upon using `imagehash.whash` on them, both produce the same hash aka `ffe3c381818181f7`. 
I'm not sure how wavelet hashing works but I'm assuming it's lossy and the shape of the images are similar causing it to mess up.
Is there a way to provide a threshold sensitivity for it (apart from hash size if possible) that could be used to handle minor cases like this?

**Comment by JohannesBuchner** [comment]
Yeah, the hash size really defines the accuracy or information loss, if you have the exact same hash. You can try to combine with a secondary hash, such as the colorhash.

**Comment by Hyperclaw79** [comment]
Thank you for the quick response. Could you please tell me, how I could
combine hashes? Thought they worked only on the images directly and
independently.

**Comment by JohannesBuchner** [comment]
Check the first for equivalence, and if yes, check the second. I guess you could also merge them into a big bitfield or concatenate the string representation.

**Comment by Hyperclaw79** [comment]
Ah! String concatenation! Should've thought of that. Thanks for the
suggestion, I'll give it a shot.
