### ISSUE TITLE
No support for 32bit python installation ?

### ISSUE THREAD

**Issue by milan-de** [JohannesBuchner/imagehash#115]
Hi guys,

I tried to install library on my Windows 10(64 bit), python 2.7.17(32 bit) enviroment but getting error message as listed below.
I am guessing that problem is because "imagehash" expect 64bit python installation right ?
As I am obligatory to use 32 bit python is there any way I could install "imagehash" on 32 bit python enviroment ?

pip version in use is: 20.0.2

regards,
Milan

C:\Python27>pip install imagehash
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03AB6C90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/imagehash/
..
ERROR: Could not find a version that satisfies the requirement imagehash (from versions: none)
ERROR: No matching distribution found for imagehash 

![inst](https://user-images.githubusercontent.com/28510933/89643100-57169780-d8b5-11ea-8bbd-054e6f64afcd.JPG)

**Comment by JohannesBuchner** [comment]
This is a pip error. You should not use python 2 any more. I think you can install python 3 on windows 32bit, and then it should work.

There seems to be a network connection issue as well.

**Comment by milan-de** [comment]
Thanks Johannes,
so can you confirm that "imagehash" lib works only with 64bits python installations ?
Problem I was getting was because I used VPN connection. If I execute installation command directly against internet, then I get another problem like here:
![grafik](https://user-images.githubusercontent.com/28510933/89649537-40763d80-d8c1-11ea-8b82-e1c6cf7a05ce.png)

Migrating to python 3 is not possible (because of project limitation) in this moment, so I guess it shall work with Python 2.7.17, right ?


regards,
Milan

**Comment by JohannesBuchner** [comment]
No, I don't think it should be limited to 64 bit.

You have pip errors, not imagehash errors. Google the error message.

Be aware that there are many projects that have dropped python 2 support. imagehash works on python 2.7, as you can see in the continuous integration testing: https://travis-ci.org/github/JohannesBuchner/imagehash/jobs/702529349

**Comment by milan-de** [comment]
Thanks Johannes,

googling did not helped much. PIP itself works well so I guess it is related to this library and some specific enviroment I have. If no one else come up with same proposal & solution I will close this ticket (or you can do it).

**Comment by JohannesBuchner** [comment]
Try installing numpy, scipy, six, pillow and PyWavelets.

Then try installing imagehash from source.

**Comment by JohannesBuchner** [comment]
I think you will have to dig up an older version of numpy & scipy, they don't support python2 officially anymore.

**Comment by JohannesBuchner** [comment]
I am closing this. If all the dependencies are successfully installed, and you still have a problem with imagehash, please reopen.
