### ISSUE TITLE
pip3 support?

### ISSUE THREAD

**Issue by barbarapernici** [JohannesBuchner/imagehash#119]
In a pipeline I am trying to install ImageHash but I get the following error

Collecting ImageHash
  Downloading ImageHash-4.1.0.tar.gz (291 kB)
ERROR: Could not find a version that satisfies the requirement pip3 (from versions: none)
ERROR: No matching distribution found for pip3

do you have any suggestions?
Thank you.

**Comment by JohannesBuchner** [comment]
This works for me. Which operating system are you using?

Alternatively, you can install from the github repository with `python3 setup.py install`

**Comment by barbarapernici** [comment]
I have ubuntu:16.04 in docker in a machine running ubuntu 20
Thank for your prompt reaction

**Comment by JohannesBuchner** [comment]
I am not sure what the problem is. ImageHash is a pure-python library, so installing it should not be platform-dependent. Perhaps one of the dependencies is not available, as far as pip could see?

**Comment by rainbowhat** [comment]
> I am not sure what the problem is. ImageHash is a pure-python library, so installing it should not be platform-dependent. Perhaps one of the dependencies is not available, as far as pip could see?

Ubuntu 20.04 

pip3 install imagehash
Collecting imagehash
  Downloading ImageHash-4.1.0.tar.gz (291 kB)
     |████████████████████████████████| 291 kB 7.4 MB/s 
Collecting PyWavelets
  Downloading PyWavelets-1.1.1-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 12.8 MB/s 
Collecting numpy
  Downloading numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 53 kB/s 
Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from imagehash) (7.2.0)
Collecting scipy
  Downloading scipy-1.5.2-cp38-cp38-manylinux1_x86_64.whl (25.7 MB)
     |████████████████████████████████| 25.7 MB 157 kB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from imagehash) (1.14.0)
Building wheels for collected packages: imagehash
  Building wheel for imagehash (setup.py) ... done
  Created wheel for imagehash: filename=ImageHash-4.1.0-py2.py3-none-any.whl size=291992 sha256=9b698faa67945a9d585ba5934552b222f230b400e3e68351edbb8ab81e766546
  Stored in directory: /root/.cache/pip/wheels/cc/57/bb/6f9f52a6d8187b8f806210e3378837aa4dc6219cd64cb99846
Successfully built imagehash
Installing collected packages: numpy, PyWavelets, scipy, imagehash
Successfully installed PyWavelets-1.1.1 imagehash-4.1.0 numpy-1.19.2 scipy-1.5.2

**Comment by JohannesBuchner** [comment]
I am presuming this is solved, or a problem of the python configuration of that particular pipeline.

**Comment by JohannesBuchner** [comment]
If not, please reopen.
