### ISSUE TITLE
Array returned by `hex_to_hash` has different shape then default hash

### ISSUE THREAD

**Issue by cmyr** [JohannesBuchner/imagehash#12]
it's not shaped to (8, 8), but (64,). I'll put up a PR for this shortly.

**Comment by cmyr** [comment]
ah I see this was resolved in the interim? Sorry.

**Comment by JohannesBuchner** [comment]
This was done in bug #11.

**Comment by cmyr** [comment]
yea, I'd checked the closed bugs but it wasn't on the list? but then saw it in a commit log. cheers.
