### ISSUE TITLE
pHash - Unable to set the 128 bit digest size

### ISSUE THREAD

**Issue by hanumantmule** [JohannesBuchner/imagehash#123]
I want 128bit hexadecimal pHash value, But I am not able to get it. I have tried all the combination of hash size and high frequency factor. 

Could you please guide me here? What are the parameters to pass to pHash call to get 128bit hash value ?

**Comment by JohannesBuchner** [comment]
128bit isn't a square. You need 2**(2 * hash_size). You could use 64 bits and leave some bits unused or 256 bit and remove some information.
