### ISSUE TITLE
FYI: Free Changes

### ISSUE THREAD

**Issue by mattsta** [JohannesBuchner/imagehash#124]
Hey Hashers,

I spent a couple days making changes to lots of things over at https://github.com/mattsta/imagehash, so feel free to browse and copy back any ideas if they seem useful.

Cleanups were either to improve modernization, understanding, or reduce feature duplication when we can use built-ins instead (example: for all the matrix to hex conversions).

It's largely unmergeable directly back because of code reformatting, but it fits our internal code organization better (and it's easy refactoring everything at once with the simple all-in-one-file organization).

**Comment by JohannesBuchner** [comment]
Good. The code in this library is meant to be easily digestible and picked up by people like you.

Pull requests are always welcome.
