### ISSUE TITLE
phash() exhibits a strong bias for repetitive bit patterns

### ISSUE THREAD

**Issue by wyverntiger** [JohannesBuchner/imagehash#13]
The hashes generated by imagehash.phash() tend to exhibit strong bias for repetitive bit patterns, thus shrinking the space of plausable hash values to something much smaller than the full 64-bit space.

  * Pull request coming momentarily with my changes

Here's an example:  I have a pile of 1442 test images.  I generated phashes for each and bucketed the results.  There were a number of hash values that identified more than one image.  Upon visual inspection most of the collided images didn't have much visual similarity.

    f4f4f4f4f4f4f4f4    - 3 images
    f5f5f5f5f5f5f5f5    - 9 images
    fcfcfcfcfcfcfcf4    - 2 images
    fefefefefefefefe    - 2 images
    6c6c6c6c6c6c6c6c    - 2 images
    0101090505050501    - 2 images
    fcf8f8f8f8fcfcfc    - 2 images
    5555555555555555    - 3 images
    0303030303030303    - 9 images
    0101010101010101    - 6 images
    9c918404e6dec7c2    - 2 images
    f4d4f4fefefefafe    - 2 images
    fafafafafafafafa    - 2 images
    fcfcfcf4f4f4f4f4    - 3 images
    9dcdcdddcddcd9dc    - 2 images
    f4f4f4f4f4fcfcfc    - 4 images
    fcfcfcfcfcfcfcfc    - 9 images

Note the repetitive bit-pattern nature of all these hashes.

I propose four changes to the imagehash code:

## Change 0    -- fix binary_array_to_int()

The implementation takes a modulus where it shouldn't and returns mathematically wrong values. This change doesn't affect the output of the library in any way, it's only used in ImageHash.__hash__(), but it's a useful function for diagnostic reasons and there's no reason not to fix it.

## Change 1-3  -- changes to the phash algorithm

1: Use a bi-directional DCT, as per [1]

2: Use the median of coefficients instead of the mean
  - as described at [2]
  - this is what phash.org's ph_dct_imagehash() does

3: Use the upper-left 8x8 coefficients, instead of skipping the left-most column
  - This change begs more debate
  - David Starkweather wrote on [3] that you want to skip the first coefficient
  - phash.org's ph_dct_imagehash() skips both the left-most column AND the top-most row.  If I understand their code, they're only using 49 coefficients instead of 64 (or 63) coefficients.  Cite: [4]
  - I would argue only the top-left-most coefficient is the DC term, and skipping the entire column or row doesn't make any sense.  If you skip the DC term then you either have a wasted bit in your hash or you get to pick some 64th coefficient to fill it -- which makes you decide if you like the horizontal or vertical axis more.  But if you include the DC term it's only going to affect a single bit of the hash, and intuitively images with good visual similarity would correlate on their DC term as well as the frequency terms.

[1] = http://stackoverflow.com/questions/15978468/using-the-scipy-dct-function-to-create-a-2d-dct-ii
[2] = http://hackerlabs.org/blog/2012/07/30/organizing-photos-with-duplicate-and-similarity-checking/
[3] = http://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html
[4] = (pHash.cpp:386)     CImg<float> subsec = dctImage.crop(1,1,8,8).unroll('x');;

After implementing these changes, I re-ran my 1442 image files and had only one bucket with more than one image:

    19b2664d98da7396    - 2 images

Upon inspection these images were nearly identical -- about a 1-degree camera rotation difference.

Pulling sample images from my library and looking for their closest phash neighbors did, of course, still yield some false positives, but in general the results empirically felt much more accurate.

I also used a small set of images to do more detailed experiments to help justify each change.

Details below:

## Experiment Driver Code

    from PIL import Image
    import imagehash

    def PHash(filepath):
      im    = Image.open(filepath)
      ph    = imagehash.phash(im)
      return ph

    def HashToString(phash):
      i     = imagehash.binary_array_to_int(phash.hash)
      return '{:016x}({:02d})'.format(i, '{:b}'.format(i).count('1'))

    def RunExperiment(hashes):
      ''' Prints an N-by-N matrix comparing each hash value to each other hash value. '''
      s       = ''
      for y in range(len(hashes)):
        s     += '\n{}: '.format(y)
        for x in range(len(hashes)):
          s   += '  {:2d}'.format(hashes[y] - hashes[x])
        s     +=  '    hash(on-bits)=' + HashToString(hashes[y])
      print('Comparison matrix:\n      ' + '   '.join([str(x) for x in range(len(hashes))]) + s)

    hashes  = (PHash('../phash1.jpeg'), PHash('../phash2.jpeg'), PHash('../phash3a.jpeg'), PHash('../phash3b.jpeg'))
    RunExperiment(hashes)

## Step 0:  Fix the binary_array_to_int() function

    testarray = np.array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1])
    list(testarray).count(1)
    6

Before:

    '{:016b}'.format(binary_array_to_int(testarray))
    '0000000101100010'
    '{:016b}'.format(binary_array_to_int(testarray)).count('1')
    4

After:

    '{:016b}'.format(binary_array_to_int(testarray))
    '1010000111000001'
    '{:016b}'.format(binary_array_to_int(testarray)).count('1')
    6

### Baseline: original implementation

    Comparison matrix:
          0   1   2   3
    0:    0   0   7  10    hash(on-bits)=fefefefefefefefe(56)
    1:    0   0   7  10    hash(on-bits)=fefefefefefefefe(56)
    2:    7   7   0   3    hash(on-bits)=fefefefefed4f4f4(49)
    3:   10  10   3   0    hash(on-bits)=fefafafefed4f4d4(46)

Very compressed hash space, the majority of bits are set

### Experiment 1:  use a bi-directional DCT

    Comparison matrix:
          0   1   2   3
    0:    0  36  29  36    hash(on-bits)=61bdf66a81857efa(36)
    1:   36   0  31  34    hash(on-bits)=af42f41ce32e30c7(32)
    2:   29  31   0  21    hash(on-bits)=b0d82f76e3996866(33)
    3:   36  34  21   0    hash(on-bits)=f8d11f864f3149c6(32)

Much higher-entropy hashes (yay!), about half the bits are set

### Experiment 2:  use median instead of mean

    Comparison matrix:
          0   1   2   3
    0:    0  28  30  30    hash(on-bits)=a4a4b4f4f4f8e8e0(32)
    1:   28   0  30  32    hash(on-bits)=aaaaaaaaaaaaaaaa(32)
    2:   30  30   0   2    hash(on-bits)=fabafafa58505050(32)
    3:   30  32   2   0    hash(on-bits)=fafafafa50505050(32)

Exactly half the bits set (yay!) but low-entropy hashes again

### Experiment 3:  use both a bi-directional DCT and the median instead of mean

    Comparison matrix:
          0   1   2   3
    0:    0  34  28  34    hash(on-bits)=21bdf66a81056afa(32)
    1:   34   0  30  34    hash(on-bits)=af42f41ce32e30c7(32)
    2:   28  30   0  22    hash(on-bits)=b0d82f76e3992866(32)
    3:   34  34  22   0    hash(on-bits)=f8d11f864f3149c6(32)

Exactly half the bits set on (yay!), high entropy (yay!)

So using bi-directional DCT yields more random-like hashes with fewer repeating bit patterns. And using the median makes the number of set bits tend to be exactly half of the available bit space. Both seem like very good changes.

### Experiment C0: skip first column, use 64 coefficients (original implementation)

    Comparison matrix:
          0   1   2   3
    0:    0  34  28  34    hash(on-bits)=21bdf66a81056afa(32)
    1:   34   0  30  34    hash(on-bits)=af42f41ce32e30c7(32)
    2:   28  30   0  22    hash(on-bits)=b0d82f76e3992866(32)
    3:   34  34  22   0    hash(on-bits)=f8d11f864f3149c6(32)

### Experiment C1: skip first row, use 64 coefficients

    Comparison matrix:
          0   1   2   3
    0:    0  32  30  36    hash(on-bits)=06437bedd4020bfd(32)
    1:   32   0  30  36    hash(on-bits)=e05ec5ed38c65c61(32)
    2:   30  30   0  20    hash(on-bits)=e661b05eedc63251(32)
    3:   36  36  20   0    hash(on-bits)=adf1a23e0d8e6293(32)

### Experiment C2: skip first row and column, use 64 coefficients

    Comparison matrix:
          0   1   2   3
    0:    0  34  32  36    hash(on-bits)=0b61bdf66a81057e(32)
    1:   34   0  32  36    hash(on-bits)=70af62f61ce32e30(32)
    2:   32  32   0  22    hash(on-bits)=f3b0d80f66e39928(32)
    3:   36  36  22   0    hash(on-bits)=56f8d11f864f3149(32)

### Experiment C3: skip first row and column, use 49 coefficients (as per phash.org)

    Comparison matrix:
          0   1   2   3
    0:    0  26  22  26    hash(on-bits)=000085ef6d4042fa(24)
    1:   26   0  24  28    hash(on-bits)=0000be174398d730(24)
    2:   22  24   0  16    hash(on-bits)=0000c2c2fed8cca8(24)
    3:   26  28  16   0    hash(on-bits)=0001e289f0d1d8c9(24)

### Experiment C4: use all 64 lowest-frequency coefficients (no skipping)

    Comparison matrix:
          0   1   2   3
    0:    0  32  30  34    hash(on-bits)=437bed94020bc5f5(32)
    1:   32   0  30  34    hash(on-bits)=5e85e938c65c618f(32)
    2:   30  30   0  18    hash(on-bits)=61b05eedc63251cd(32)
    3:   34  34  18   0    hash(on-bits)=f1a23e0d9e62938d(32)

Image 3 is similar to image 2 (same person, similar camera angle, different pose). Image 0 and 1 are similar to 2 or 3 only in that they all have a sky, a ground, and a horizon.

The best spread we got between similar and not-similar results was 16: cases C1 and C4

Case C3 had a spread of 10, but used 77% of the bits to do it.

Normalizing C3 as if it used 64 bits yields a spread of 13  (= 10*64/49)

My preference is to go with C4.  C3 may be the phash.org implementation but I see no benefit to throwing out 15 bits worth of data.  C2 is arguably what phash.org might have wanted instead, using 15 higher-frequency coefficients instead of the 15 lowest-frequency coefficients, but it doesn't perform as well as C4.  C1 and C0 seem arbitrary to me, choosing to favor horizontal data over vertical data or vise-versa.

Of course it would make sense to run large-scale experiments on thousands of human-classified test samples.  But that's resources I don't have access to at this time.

##  Pull Request

A pull request with my changes should be coming along momentarily.

**Comment by JohannesBuchner** [comment]
Wow, it looks like you did quite a bit of work there!
Thank you!
Let me comment on your suggested code changes in a minute

**Comment by JohannesBuchner** [comment]
Thank you for the patch. Please try out the newest version, https://pypi.python.org/pypi/ImageHash/1.0
