### ISSUE TITLE
Deprecated notice: numpy bool

### ISSUE THREAD

**Issue by qathom** [JohannesBuchner/imagehash#136]
Hello,

Thanks for making this great library!

I'm receiving a deprecation notice saying that numpy.bool should be replaced in [imagehash.py](https://github.com/JohannesBuchner/imagehash/blob/d7dffec20dcfc7d1afac90ad7d447cd06240087c/imagehash.py#L505)

Should the library be compatible with recent versions of numpy now?

Notice:
```
  /opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/imagehash.py:525: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    unassigned_pixels = numpy.full(pixels.shape, True, dtype=numpy.bool)
```

**Comment by JohannesBuchner** [comment]
It seems like replacing numpy.bool with bool would do the job. Would you submit a pull request?

**Comment by qathom** [comment]
Hi @JohannesBuchner 
Thanks for your prompt reply!
Yes with pleasure. Please find my pull request: #137
