### ISSUE TITLE
remove "six"

### ISSUE THREAD

**Issue by Yay295** [JohannesBuchner/imagehash#141]
It is currently only imported in two files: `tests/test_whash.py` and `find_similar_images.py`. In `tests/test_whash.py` it is used for `six.assertRaisesRegex`, and its only use in `find_similar_images.py` is commented out. Since it's only used for that one thing I think it should be possible to write a local replacement for it and remove the dependency.

**Comment by JohannesBuchner** [comment]
Sounds good. Can you draft a PR?
