### ISSUE TITLE
Identifies similar images in the directory

### ISSUE THREAD

**Issue by wamm0909** [JohannesBuchner/imagehash#143]
Can you please suggest me ,which parameter i need to fill to get output. I have 10,000 images 1.jpg ...n.jpg. I want to find similarity between them. How shall i do it? I would be greatful . Thanks; 
i fill this. :  '  sys.stderr.write('phash','\dog')',   but not work
` def usage():
sys.stderr.write("""SYNOPSIS: %s [ahash|phash|dhash|...] []
Identifies similar images in the directory.
Method:
ahash: Average hash
phash: Perceptual hash
dhash: Difference hash
whash-haar: Haar wavelet hash
whash-db4: Daubechies wavelet hash
(C) Johannes Buchner, 2013-2017
""" % sys.argv[0])
sys.exit(1)'

**Comment by uly94** [comment]
I have the same problem as you. Waiting for help, please.

**Comment by JohannesBuchner** [comment]
For example:

`python3 find_similar_hash.py ahash tests/data/`

to apply the ahash algorithm to find similar images in the tests/data directory.

**Comment by uly94** [comment]
It didn't worked. I solved my problem creating a script that runs imagehash library

**Comment by JohannesBuchner** [comment]
If this problem is still there, please re-open this bug with a detailed description what you tried, what you expected and what actually happened.
