### ISSUE TITLE
phash - images don't match with smaller hash size

### ISSUE THREAD

**Issue by Yay295** [JohannesBuchner/imagehash#145]
I have two nearly identical images (one is a re-jpeg-compressed version of the other), and with the default hash size of 8 they match with 'ebda852592c4b0b7'. But when I changed the hash size to 6 these images no longer match: 'eb6849933' vs 'eb6849935'.

I'm storing these hashes in a database, so I was hoping to be able to compare them as strings, and just use a smaller hash size for a less strict comparison. Is there a problem with the algorithm, or does it just not work like that?

**Comment by JohannesBuchner** [comment]
The hash size sets the size of the downsized image, from which the hash is computed.  So it will be different.

Most databases support hamming distance searches if you store in the right format, maybe that's what you want.
