### ISSUE TITLE
How to use find_similar_images.py to find images?

### ISSUE THREAD

**Issue by uly94** [JohannesBuchner/imagehash#148]
I'm wondering how to use/modify the find_similar_images.py file to find similar images within a folder.
Thank you in advance.

**Comment by JohannesBuchner** [comment]
see here: https://github.com/JohannesBuchner/imagehash/issues/143#issuecomment-922809341

**Comment by uly94** [comment]
Ok now worked. But where I can show the result? Where I can see similar images?

**Comment by JohannesBuchner** [comment]
The output should tell you which image files are similar to each other.

If you are looking for something more customized, you will need to adapt the script, or use the library, for example to build a GUI for your needs. The script is just one example how the library can be used.

**Comment by uly94** [comment]
No, it doesn't show anything as output.

**Comment by JohannesBuchner** [comment]
Maybe there are no similar images in that particular folder?
