### ISSUE TITLE
AssertionError: ('ImageHashes must be of the same shape!', (64,), (8, 8))

### ISSUE THREAD

**Issue by whypro** [JohannesBuchner/imagehash#15]
I need to save the hex hash string to my database, and read it later. But after I create a ImageHash instance using the hex string by hex_to_hash() method, 'h2 - h1' raise an exception. I wonder if it is a bug of hex_to_hash() method? I have no idea about that. I'm not good at NumPy.  

    from PIL import Image
    import imagehash
    
    i1 = Image.open('1.jpg')
    i2 = Image.open('1.png')
    
    h1 = imagehash.dhash(i1)
    print h1
    # d3b7cf4ebd183140
    h2 = imagehash.dhash(i2)
    print h2
    # d3b7cf4ebd183140
    
    print h2 - h1
    # 0
    
    h3 = imagehash.hex_to_hash('d3b7cf4ebd183140')
    print h3 - h2
    # Traceback (most recent call last):
    #   File "<stdin>", line 1, in <module>
    #   File "/usr/lib/python2.7/site-packages/imagehash/__init__.py", line 64, in __sub__
    #     assert self.hash.shape == other.hash.shape, ('ImageHashes must be of the same shape!', self.hash.shape, other.hash.shape)
    # AssertionError: ('ImageHashes must be of the same shape!', (64,), (8, 8))

    print h3 - h1
    # Traceback (most recent call last):
    #   File "<stdin>", line 1, in <module>
    #   File "/usr/lib/python2.7/site-packages/imagehash/__init__.py", line 64, in __sub__
    #     assert self.hash.shape == other.hash.shape, ('ImageHashes must be of the same shape!', self.hash.shape, other.hash.shape)
    # AssertionError: ('ImageHashes must be of the same shape!', (64,), (8, 8))

**Comment by steven991** [comment]
print h3 - imagehash.hex_to_hash(str(h2))
print h3 - imagehash.hex_to_hash(str(h1))

This could work?

**Comment by JohannesBuchner** [comment]
It would. Maybe I should flatten the array in __sub__ and __eq__, and __ne__

**Comment by JohannesBuchner** [comment]
Thank you for reporting this issue.
