### ISSUE TITLE
load imagehash.crop_resistent_hash

### ISSUE THREAD

**Issue by themetalleg** [JohannesBuchner/imagehash#160]
Hi,

I am saving the image hashes of the crop_resistent_hash in a database with:
`chash = imagehash.crop_resistant_hash(img).__str__()`
Now I want to load this hash again, but cannot find a way.

The other hashes I can load with either hex_to_hash or hex_to_flathash, but this one not.
I also tried to work with ImageMultiHash, but no success.

Would be great if somebody could help.

**Comment by fayyazraja** [comment]
hi, did you find anything for it?

**Comment by JohannesBuchner** [comment]
You can make a string from a ImageHash object with str()

You can make a string from a ImageMultiHash object with str(), which is a comma-separated list of what the above would return.

For the reverse:

You can make a ImageHash object from a string with hex_to_(flat)hash

You can make a ImageMultiHash object by passing a list of ImageHash objects.

**Comment by JohannesBuchner** [comment]
fixed with #166
