### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by PeterJCLaw** [JohannesBuchner/imagehash#163]
Thanks for providing this great library.
I can see that in the past wheels have been uploaded to PyPI, however they seem to be absent for 4.2.1 (the latest at the time of writing).
Would it be possible to upload wheels for that version too?

**Comment by JohannesBuchner** [comment]
Hi @PeterJCLaw, thanks for pointing this out. I made a new release today (4.3) with wheels. 

Do you think it is crucial that I add wheels to the previous 4.2.1 release?

**Comment by PeterJCLaw** [comment]
Thanks!
Given the new release has wheels I'd say it's not critical to add them to the old one.
