### ISSUE TITLE
PHash() is not throwing out high-frequency image data.

### ISSUE THREAD

**Issue by wyverntiger** [JohannesBuchner/imagehash#17]
As of commit:  https://github.com/JohannesBuchner/imagehash/commit/481148afa79eca6c80b853ecccabc128d7cef514

The phash() and phash_simple() algorithms are no longer tossing out high-frequency image data.

The rest of this issue description is the same as the comment I wrote on that commit:

----

On average_hash and dhash the hash_size parameter is used to indicate how small to make the sub-sampled image, which directly becomes the number of bits in the resulting hash value.

But phash (and phash_simple) there's two steps of subsampling, not one. The first subsample is when we reduce the image, and the second subsample is when we select which DCT coefficients to use. The second subsample determines the number of bits in the resulting hash value.

These two steps really need to be done at different sizes. The whole reason phash works is because it tosses out high-frequency image data, that which is most likely to be different in similar-looking images, and it keeps only the low-frequency data. This happened in the past because we downsized the image to 32x32 pixels (subsample 1) which generated 32x32 DCT coefficients, and then we kept only 8x8 of the DCT coefficients (subsample 2).

But after this commit, the algorithm is keeping ALL the DCT coefficients. It downsizes to 8x8 pixels and keeps all 8x8 coefficients. It no longer throws out high-frequency data.

This means that similar images that would have hashed to similar phash values are now much more likely to differ by more bits in their phash values, because that high-frequency data is being included.

(You can also easily show that phash_simple is returning fewer bits than expected because it's basically running off the edge of the dct matrix)

**Comment by JohannesBuchner** [comment]
Ah, you are right. Could you take a quick look at the latest commit and check if that solves it?

**Comment by wyverntiger** [comment]
Looks good to me, thanks!  :)
 ~W
