### ISSUE TITLE
store crop_resistant hash in database

### ISSUE THREAD

**Issue by xomarnd** [JohannesBuchner/imagehash#170]
I had an idea to store crop_resistant_hash in the database and search them.
 
What is the best way for me to pass an object to the database and then get it from there and compare it with others using your library?

**Comment by JohannesBuchner** [comment]
This question seems to be a combination of https://github.com/JohannesBuchner/imagehash/issues/160 (which I have not answered yet, and will do now).

Database-related issues (efficient search) have been discussed at https://github.com/JohannesBuchner/imagehash/issues/127#issuecomment-771550697
