### ISSUE TITLE
Dependency to six library

### ISSUE THREAD

**Issue by rbuffat** [JohannesBuchner/imagehash#178]
Imagehash 4.3.0 tries to import six, but it is not declared as a dependency for Python 3.10: 

https://github.com/osmlab/editor-layer-index/actions/runs/3120554190/jobs/5061223939
https://github.com/osmlab/editor-layer-index/blob/gh-pages/requirements.txt

```
Traceback (most recent call last):
  File "/home/runner/work/editor-layer-index/editor-layer-index/scripts/sync_wms.py", line 28, in <module>
    import imagehash
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/imagehash/__init__.py", line 155, in <module>
    from six.moves.collections_abc import Callable
ModuleNotFoundError: No module named 'six'
Error: Process completed with exit code 1.
```

There seems to be a fix already in master, but I'm not sure if this works in all cases. 
I would suggest something like this (not tested):

```
# not sure when typing.Callable was first introduced. Maybe 3.5?, But I'm not sure if such old python version are still supported by ImageHash
if sys.version_info >= (3, 6):
    # https://stackoverflow.com/questions/65858528/is-collections-abc-callable-bugged-in-python-3-9-1
    if sys.version_info > (3, 9, 1):
        from collections.abc import Callable
    else:
        from typing import Callable
    try:
        MeanFunc = Callable[[NDArray], float]
        HashFunc = Callable[[Image.Image], ImageHash]
    except TypeError:
        MeanFunc = Callable  # type: ignore
        HashFunc = Callable  # type: ignore
```

**Comment by JohannesBuchner** [comment]
oh no. six is a requirement, yes. I added it in the latest commit: https://github.com/JohannesBuchner/imagehash/commit/ba29983615d482201ce9a3e11f19f98e1220cc29

Can you have a look whether this would solve the issue?

**Comment by SpangleLabs** [comment]
I thought six was removed a while back: https://github.com/JohannesBuchner/imagehash/issues/141 and the recent https://github.com/JohannesBuchner/imagehash/pull/172

**Comment by JohannesBuchner** [comment]
Right, I forgot about that.

**Comment by JohannesBuchner** [comment]
ImageHash supports back to 2.7

**Comment by JohannesBuchner** [comment]
I made a release, 4.3.1. Can you please test whether it works for you?

**Comment by JohannesBuchner** [comment]
Github Actions test these versions: 2.7, 3.5, 3.6, 3.9.1, 3 (latest, 3.10.4 at the moment)

It claims to work for all of these without the modification you propose.

**Comment by JohannesBuchner** [comment]
Sorry for not pushing a release earlier.

**Comment by JohannesBuchner** [comment]
> > I made a release, 4.3.1. Can you please test whether it works for you?
> 
> @JohannesBuchner Thanks for creating a new release that fast! The github action that was affected will trigger automatically on Sunday. I will report back if it solved the issue or not. But I'm very positive that it will.

OK, please reopen if it is still an issue.

> > Github Actions test these versions: 2.7, 3.5, 3.6, 3.9.1, 3 (latest, 3.10.4 at the moment)
> 
> I appreciate that you are willing to support that many old Python versions. In case you are not aware, [Python 2.7 reached its end of life on January 1, 2020](https://www.python.org/doc/sunset-python-2/). A lot of Python packages follow roughly the numpy deprecation policy of supporting Python versions for 42 months: https://numpy.org/neps/nep-0029-deprecation_policy.html

I am aware. I might drop it once things really start to break, but it's not that bad atm.
