### ISSUE TITLE
hash with z-transform

### ISSUE THREAD

**Issue by hazenne7** [JohannesBuchner/imagehash#179]
NOT AN ISSUE, just wondering what z-transform does to the image so it can change its hash value.

**Comment by JohannesBuchner** [comment]
code is here: https://github.com/JohannesBuchner/imagehash/blob/d7dffec20dcfc7d1afac90ad7d447cd06240087c/examples/hashimages.py#L37

Maybe it is not necessary. I thought it would enhance contrast. For example, if you have bright and dark parts in an image, the hash by default would distinguish the two parts but not see patterns within. A z-transform brings the contrast closer together.

**Comment by hazenne7** [comment]
Noted! Thanks for your reply, really appreciate it!
