### ISSUE TITLE
how to encode an <class 'imagehash.ImageHash'> object into mongodb?

### ISSUE THREAD

**Issue by chuckytah** [JohannesBuchner/imagehash#18]
Hello, 

I am new to python/pymongo and I am in trouble when I try to save imagehash infos to a mongodb database...  

File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
bson.errors.InvalidDocument: Cannot encode object: array([[False,  True,  True,  True,  True, False,  True,  True],
       [ True, False, False, False,  True,  True, False, False],
       [False, False,  True, False, False,  True,  True, False],
       [False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True, False, False]], dtype=bool)

Sorry if it is a dumb question, but could you help me solve this? :/

thanks

**Comment by JohannesBuchner** [comment]
You can convert the hash object to a string (str(hash)) which gives you a hex encoding. 
You can decode it again with hex_to_hash.

**Comment by chuckytah** [comment]
@JohannesBuchner you said "You can convert the hash object to a string (str(hash)) which gives you a hex encoding." and then cand decode it with hex_to_hash, but how? 

how to get str to hash again?
