### ISSUE TITLE
A tutorial on creating a reverse image search

### ISSUE THREAD

**Issue by KDJDEV** [JohannesBuchner/imagehash#186]
I worked on a project in which I wanted to store hashes generated with this library in a database and use fast hamming distance searches to create a reverse image search.

I saw that you said that if someone were to write a blog post on how to do this it would be a great contribution. So, I did.

[https://github.com/KDJDEV/imagehash-reverse-image-search-tutorial](https://github.com/KDJDEV/imagehash-reverse-image-search-tutorial)

In this tutorial I use PostgreSQL and [this extension](https://github.com/fake-name/pg-spgist_hamming), and I show how you can create a reverse image search using hashes generated by this library.

Unfortunately this tutorial does not explain how to use variable hashes like the CropResistantHash, as is asked about in [this issue](https://github.com/JohannesBuchner/imagehash/issues/127). However, most of the hashes in this library are not variable, so I think it could still be useful.

Anyways, I thought I would mention that I created this so that hopefully it can be of some use to someone.

**Comment by JohannesBuchner** [comment]
Fantastic, thank you.

I added it here:
https://github.com/JohannesBuchner/imagehash#efficient-database-search
