### ISSUE TITLE
Maximum possible difference

### ISSUE THREAD

**Issue by shanemcquillan** [JohannesBuchner/imagehash#19]
Hi Johannes,

This is a quick question more than an issue, though it would be helpful for you to add it to your docs. What is the maximum possible difference between two images using the hashing approach?

max(hash1 - hash2) = ?

I'm interested in the normalizing the value to give a value between 0 and 1, though this may not make sense. I'd be interested to know your thoughts.

Thanks,

Shane

**Comment by blakebjorn** [comment]
Not the maintainer, but the max difference is the size of the hash (default is 8 x 8, so 64).

For instance (1x4 hash):
[1, 1, 0, 0] - [0, 0, 1, 1] = hamming distance of 4

**Comment by shanemcquillan** [comment]
I thought so, thanks Blake.
