### ISSUE TITLE
Alternative to scipy.fftpack

### ISSUE THREAD

**Issue by dt99jay** [JohannesBuchner/imagehash#191]
Many thanks for this library, I'm finding it very helpful. I'm getting the best results with phash, but would like to generate hashes in an AWS Lambda function. Lambdas have a 250Mb limit on dependencies, and SciPy takes up about 200Mb. I can probably just about squeeze imagehash and the other dependencies I need into the last 50Mb, but thought I'd check if there's an alternative to SciPy's FFT?

**Comment by JohannesBuchner** [comment]
Have you tried googling for "FFT library python"?

**Comment by dt99jay** [comment]
I see [Numpy has some FFT functions](https://numpy.org/doc/stable/reference/routines.fft.html) but not the [DCT that phash uses](https://github.com/JohannesBuchner/imagehash/blob/master/imagehash/__init__.py#L276C68-L276C68)

**Comment by JohannesBuchner** [comment]
I don't know. Closing this now.

But I saw https://stackoverflow.com/questions/62546019/aws-lambda-how-to-manage-deployment-packages-greater-than-250mb

**Comment by JohannesBuchner** [comment]
(by googling "Lambdas have a 250Mb limit on dependencies")
