### ISSUE TITLE
AttributeError: module 'imagehash' has no attribute 'average_hash'

### ISSUE THREAD

**Issue by prescriptionlifeline** [JohannesBuchner/imagehash#192]
Here's my code:

```
from PIL import Image
import imagehash
import sys

hash = imagehash.average_hash(Image.open(sys.argv[1]), 16)
print(hash)
```
`AttributeError: module 'imagehash' has no attribute 'average_hash'` is the error I'm getting.

I'm running Python 3.5.3 and ImageHash 4.3.1.

I had it working before but now it's not and I have no idea as to why.

**Comment by hamirmahal** [comment]
I ran into the same issue today.
