### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'.

### ISSUE THREAD

**Issue by ChristophSBG** [JohannesBuchner/imagehash#202]
When using Python 3.12 you get the following error message when trying to install imagehash via pip:

`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'.`

From what I researched it is due to Python 3.12 not supporting pkgutil.ImpImporter anymore: https://docs.python.org/3/whatsnew/3.12.html

**Comment by JohannesBuchner** [comment]
duplicate of https://github.com/JohannesBuchner/imagehash/issues/194
