### ISSUE TITLE
is possible to convert back from phash to image?

### ISSUE THREAD

**Issue by kucingkembar** [JohannesBuchner/imagehash#203]
sorry for the stupid question, and my broken English,
as the title says, I need to convert phash code to an image,
why? 
because there is a site (https://metadataapi.net/) that has a search engine that uses phash as the keyword,
but no matter I input the phash based on my pic, the site result is "data not found"
I want to see pic format that is acceptable to the site,

thank you, have a nice day

**Comment by JohannesBuchner** [comment]
If you have a large data base of phashes, you can search for a phash in it, which will give you similar images.
