### ISSUE TITLE
Different hashes with the same object

### ISSUE THREAD

**Issue by FelipeLael** [JohannesBuchner/imagehash#209]
I'd like to know if it's possible to identify the similarity or difference between two images if both images have the same object, the only difference being the size of that object in the image.
![alpha_edges1](https://github.com/JohannesBuchner/imagehash/assets/148511567/560a5045-bbc4-4ea2-94f7-e38eeff60268)
![alpha_edges](https://github.com/JohannesBuchner/imagehash/assets/148511567/ab08b183-a281-496e-8fa4-ec8d236ad494)

These are the two images, the shape of the object is visibly the same as each other, so the most obvious choice would be to use imagehash to compare them, performing a simple code with phash shows that both images are different.

**Comment by JohannesBuchner** [comment]
Crop-resistant hashing should do this potentially. imagehash.crop_resistant_hash
