### ISSUE TITLE
Using sizes other than 8

### ISSUE THREAD

**Issue by destrugter** [JohannesBuchner/imagehash#21]
I love this project and am currently using it in one of mine. The thing is, you allow me to set a hash_size to something other than 8, but you won't let the person use the function hex_to_hash on the hex generated by using a size greater than 8. Am I doing something wrong, or was this an oversight?

**Comment by JohannesBuchner** [comment]
See issue https://github.com/JohannesBuchner/imagehash/issues/20 
I suppose this could become part of the official code with a generic handling. Submit a patch if you are keen?
I suppose parsing of non-square shapes can not work automatically ...

**Comment by destrugter** [comment]
Oh, ok. Sorry, I didn't mean to start a new issue on this. Thanks.
