### ISSUE TITLE
Hash comparison performance

### ISSUE THREAD

**Issue by mdevans** [JohannesBuchner/imagehash#22]
Hi Johannes - thanks for an elegant implementation of these perceptual hash algorithms.

A performance enhancement suggestion for hash comparison (_sub_):  

My understanding is that:

self.hash.flatten() != other.hash.flatten()

will do a boolean compare for each element in the hash array

Optimising this via the clever bitCount() below could be useful when comparing large hash sets 
from: https://wiki.python.org/moin/BitManipulation

def bitCount(int_type):
       count = 0
       while(int_type):
       int_type &= int_type - 1
       count += 1
       return(count)

**Comment by JohannesBuchner** [comment]
Closing until demonstrated that that would be faster than numpy.array_equal.

**Comment by redraw** [comment]
Hey thanks for the lib! this is minor, but would it be necessary to flatten the array before comparison if both should have the same shape?
Just founded `numpy.count_nonzero` as a slightly faster alternative to calculate the Hamming distance,
```
In [4]: print h1, type(h1)
425a5a4e58d8c8eb <class 'imagehash.ImageHash'>

In [5]: print h2, type(h2)
62682c18d8c84b5a <class 'imagehash.ImageHash'>

In [6]: %timeit np.count_nonzero(h1.hash != h2.hash)
The slowest run took 28.10 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 882 ns per loop

In [7]: %timeit (h1.hash.flatten() != h2.hash.flatten()).sum()
The slowest run took 7.25 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.3 µs per loop
```

**Comment by JohannesBuchner** [comment]
How does `%timeit (h1.hash != h2.hash).sum()` compare?

**Comment by redraw** [comment]
`In [8]: %timeit (h1.hash != h2.hash).sum()
The slowest run took 9.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.65 µs per loop`

**Comment by JohannesBuchner** [comment]
Commit 33023ba addresses this. Please test if it works for you.
