### ISSUE TITLE
Memory leak in wavelet hash

### ISSUE THREAD

**Issue by gtoonstra** [JohannesBuchner/imagehash#25]
Looks like wavelet hash implementation has a memory leak. I'm processing 600k images and memory keeps going up. When using the other hash implementation, memory usage does not accumulate.

**Comment by gtoonstra** [comment]
Looks like an issue in pywt.

**Comment by dmpetrov** [comment]
It looks like in pywt is optimized for big images. They use some special memory optimization technics:

"Extending data in context of PyWavelets does not mean reallocation of the data in computer’s physical memory and copying values, but rather computing the extra values only when they are needed. This feature saves extra memory and CPU resources and helps to avoid page swapping when handling relatively big data arrays on computers with low physical memory."

I'll try to contact them and solve the issue.

**Comment by JohannesBuchner** [comment]
Please leave a link to the upstream pywt bug, and then I will close this bug.

**Comment by dmpetrov** [comment]
Here it is: https://github.com/PyWavelets/pywt/issues/180

**Comment by JohannesBuchner** [comment]
So that bug was closed, but there is a memory leak remaining in pillow (and possible the old PIL).
imagehash uses pillow already, so this should be resolved if user code uses pillow as well and the remaining pillow memory leak is fixed.
