### ISSUE TITLE
dhash computes difference vertically, not horizontally

### ISSUE THREAD

**Issue by JohannesBuchner** [JohannesBuchner/imagehash#28]
The dhash function computes the pixel difference between vertically adjacent pixels.
But if we follow http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html the difference should be horizontal.
This might make a difference for e.g. images of landscapes.

**Comment by fxolivia** [comment]
![dhash](https://cloud.githubusercontent.com/assets/21353995/18192627/0bff8b90-7111-11e6-8560-8eb3bd2b3ce0.png)
resize() command in webpage : http://infohost.nmt.edu/tcc/help/pubs/pil/pil.pdf
![resize](https://cloud.githubusercontent.com/assets/21353995/18192642/22955c54-7111-11e6-8a61-40636d6cf3c4.png)
previous you program : image = image.convert("L").resize((hash_size + 1, hash_size), Image.ANTIALIAS) is right, it convert image into 9*8, width is 9, height is 8. so the matrix of pixels need to be 8*9 lines, 8 rows, 9 columns.
This is your new version result:
![newcompare](https://cloud.githubusercontent.com/assets/21353995/18192758/f93e44a0-7111-11e6-9aa4-b2cff8e5c5d4.png)
Program should be modified like: 
![program_modify](https://cloud.githubusercontent.com/assets/21353995/18192844/b42741f4-7112-11e6-80a2-7db87cc0a54e.png)

**Comment by JohannesBuchner** [comment]
Oh this is confusing. Thank you. Could you have another look?

**Comment by JohannesBuchner** [comment]
New code is like fx_dhash now.
