### ISSUE TITLE
Version 3 not in pypi repo

### ISSUE THREAD

**Issue by PAK90** [JohannesBuchner/imagehash#30]
Not sure if this was the right place, but I want to upgrade my imagehash version and doing `pip install imagehash --upgrade` still gives me the 2.2 version, presumably because [the pypi page hasn't been updated with v3](https://pypi.python.org/pypi/ImageHash).

**Comment by JohannesBuchner** [comment]
Please try again. If you have time, please test the dhash function.

**Comment by PAK90** [comment]
Sorry, no luck. The pypi page is still showing v2.2 and so is the tar.gz file when I do `pip install imagehash --upgrade`.

**Comment by JohannesBuchner** [comment]
Sorry, I had my gpg setup wrong. Please try once again.

**Comment by PAK90** [comment]
Yep, it's good now, I was able to upgrade, thanks :). The dhash results are very different to the phash results, which I'm not sure was the case in v2.2, but I don't mind since I'm using phashes in my application anyway.

As an aside; I have a database of ~30,000 phashes and right now I'm looping through all of them attempting to find the one with the lowest Hamming distance to my test hash (just by doing `testHash - dbHash`); do you know of a quicker way (this currently takes me 5-10 seconds)? I was told sorting the hashes and doing binary tree searching (i.e. treating the hashes like normal numbers) wouldn't work.

**Comment by JohannesBuchner** [comment]
You could flatten each hash and store all of them into a large numpy 2d array (Nxhashsize). Then check if equal to your test hash (of shape 1 x hashsize), i.e. (A != b).sum(axis=1), and do argmin on the result (size N).

**Comment by PAK90** [comment]
OK, I'm still new to this so I have a few questions... how do you flatten a hash (and what exactly is flattening doing to it)? The equality check seems unnecessary since I know my test hash from a video feed will never exactly equal any of the stored hashes in the database. Doing argmin on the result of the hash difference of all hashes; will that be any quicker than what I'm doing now?

**Comment by JohannesBuchner** [comment]
Doing testHash - dbHash calls ImageHash.__sub__. Try to understand that function. What I am suggesting is that you re-implement that function, but vectorized.

**Comment by PAK90** [comment]
OK... from what I see, `flatten` must be doing some iterative process since you're summing the differences of each digit in the hashes. What does `flatten` do exactly?

**Comment by deveyNull** [comment]
Hey everyone, sorry for not getting involved with this earlier, saw the comment on taking 5-10 seconds for a ~30,000 image database and remembered I forgot to merge the stuff I've done.

I figured out perceptual hashing databases last year, one of my implementations does lookups on 170 million hashes in constant time, the one I have on github is only constant time out to 17 million, but I assume it will fit any of your applications. https://github.com/deveyNull/phistOfFury

I forked my original repo from this one, and I was working on a merge but it wound up being way too much work because of all the changes. If you are interested we can make that happen, it would be great for the community, makes perceptual hashing applicable at scale in the real world.

And no, I haven't written a paper yet. If one more person tells me to I'm gonna keep putting it off.

**Comment by PAK90** [comment]
Wow, that looks like exactly the sort of thing I need. Can you point the `hashDirectory` command to a folder full of folders of images, or is that too nested? If not I assume I can pass the same `flatDBName` as I iterate over all my folders. Also, what format does the flat database have to be in? Right now I use a list of dictionaries since I need additional info for each image besides its phash, would that work?

**Comment by JohannesBuchner** [comment]
numpy.flatten makes a 1d array out of the 2d array (matrix) where the hash is stored. != compares element-wise if the things are the same, numpy.sum() adds the number of differences, which gives the Hamming distance.

What I am suggesting is:

I suspect you are doing something like this now:

```
diff, closestdbHash = min([(dbHash - testhash, dbHash) for dbHash in db])
```

which does the same as

```
diff, closestdbHash = min([((dbHash.hash != testhash.hash).sum(), dbHash) for dbHash in db])
```

You can store your DB as a 2d matrix:

```
arr = []
for dbHash in db:
    arr.append(dbHash.hash.flatten())
arr = numpy.array(arr)
```

Then you can do the comparison against all at the same time:

```
binarydiff = arr != testhash.hash.reshape((1,-1))
hammingdiff = binarydiff.sum(axis=1)
closestdbHash_i = numpy.argmin(hammingdiff)
closestdbHash = db[closestdbHash_i]
```

This will be very, very fast.

**Comment by JohannesBuchner** [comment]
Hi @deveyNull . I just had a brief look at your repo -- looks like you did a lot of work! 
Btw, the imagehash source code is not based on photohash at all, it is completely independent. Only github shows it that way. Please also don't forget to put a LICENCE file in your repo.

**Comment by deveyNull** [comment]
@PAK90 
Let's move this conversation to my repo so we don't blow up the notifications for this one

@JohannesBuchner 
If you could help me navigate the licensing that would be great, what do you have it licensed under? I'm not sure what to do with whatever you have right now. Also, if you want to merge any of the changes let me know.

**Comment by JohannesBuchner** [comment]
@deveyNull if you want the easy route, copy the LICENCE file from my repo. It is the BSD 2-clause license, which is extremely liberal. Add yourself as author/copyright holder, Your Name (C) 2015 and mention the copyright and license in the top of your source file.

**Comment by deveyNull** [comment]
Oh great, all I have to do is copy it? BSD 2 is perfect, why (C) 2015 though? And where do I put your name in it? Thank you very much.

**Comment by PAK90** [comment]
@JohannesBuchner I think I see now; I'll give that a shot tonight when I get back to my home PC. I'm guessing the `closestdbHash_i` value is the index of the closest hash? If that's the case that's great because I can then use that same index to look up the dictionary I want from my list (assuming I generate the 2d matrix from that list).

**Comment by JohannesBuchner** [comment]
@PAK90 correct.

**Comment by PAK90** [comment]
@JohannesBuchner I tried your solution and it worked first time, it's fantastic. The total time to do those steps is just around 0.21 seconds, which is amazing. I had a question though; I still want a maximum threshold difference to be defined before I accept a match. Before, when I was calculating the Hamming distance, I could easily define this with a single number (usually 60 with a 48-digit hash). Now, the `hammingDiff` variable is an array, so is there a way I can get a single difference 'score' out of this process?

**Comment by JohannesBuchner** [comment]
Use `hammingdiff[closestdbHash_i]`

**Comment by PAK90** [comment]
Ah yeah, that did the trick, thanks :)

One thing I noticed is that the phashes aren't rotationally independent. I can have my test image from the video stream be an upside down version of the regular image, but the hash is completely mismatched until I turn it right side up. Is there a trick when it comes to testing rotated images, or do I have to test the rotated and non-rotated versions individually?

**Comment by JohannesBuchner** [comment]
Yes, you would need to test the rotated/flipped versions indivitually, **but** you can apply the rotation to the hash. Use numpy.fliplr, numpy.flipud, numpy.rot90 on testhash.hash.

**Comment by mynameisvinn** [comment]
@PAK90 @JohannesBuchner ive been using approximate nearest neighbor to loop through a collection of hashes. annoy was developed by spotify to find similar users/songs for their recommender system. 

https://github.com/spotify/annoy

hope this helps!
