### ISSUE TITLE
Unable to install the library "--single-version-externally-managed --compile" failed with error code 1"

### ISSUE THREAD

**Issue by dance2die** [JohannesBuchner/imagehash#39]
**OS**: Windows 10
**Python Version:** 3.5.0
**Pip Version**: 9.0.1

I am getting following error message while trying to install (`pip install ImageHash`) the library.

	Command "c:\misc\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DANCE2~1\\AppData\\Local\\Temp\\pip-build-otq1zs_f\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DANCE2~1\AppData\Local\Temp\pip-ei4og5fl-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DANCE2~1\AppData\Local\Temp\pip-build-otq1zs_f\scipy\

Here is the full message. Let me know should you require other information.

	c:\Users\dance2die>pip install ImageHash
	Collecting ImageHash
	  Using cached ImageHash-3.1.tar.gz
	Requirement already satisfied: numpy in c:\misc\python\python35-32\lib\site-packages (from ImageHash)
	Collecting scipy (from ImageHash)
	  Using cached scipy-0.18.1.tar.gz
	Collecting pillow (from ImageHash)
	  Using cached Pillow-3.4.2-cp35-cp35m-win32.whl
	Collecting PyWavelets (from ImageHash)
	  Using cached PyWavelets-0.5.1-cp35-none-win32.whl
	Installing collected packages: scipy, pillow, PyWavelets, ImageHash
	  Running setup.py install for scipy ... error
		Complete output from command c:\misc\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DANCE2~1\\AppData\\Local\\Temp\\pip-build-otq1zs_f\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DANCE2~1\AppData\Local\Temp\pip-ei4og5fl-record\install-record.txt --single-version-externally-managed --compile:

		Note: if you need reliable uninstall behavior, then install
		with pip instead of using `setup.py install`:

		  - `pip install .`       (from a git repo or downloaded source
								   release)
		  - `pip install scipy`   (last SciPy release on PyPI)

		lapack_opt_info:
		openblas_lapack_info:
		  libraries openblas not found in ['c:\\misc\\python\\python35-32\\lib', 'C:\\', 'c:\\misc\\python\\python35-32\\libs']
		  NOT AVAILABLE

		lapack_mkl_info:
		  libraries mkl_rt not found in ['c:\\misc\\python\\python35-32\\lib', 'C:\\', 'c:\\misc\\python\\python35-32\\libs']
		  NOT AVAILABLE

		atlas_3_10_threads_info:
		Setting PTATLAS=ATLAS
		c:\misc\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:639: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
		  warnings.warn('Specified path %s is invalid.' % d)
		<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
		  NOT AVAILABLE

		atlas_3_10_info:
		<class 'numpy.distutils.system_info.atlas_3_10_info'>
		  NOT AVAILABLE

		atlas_threads_info:
		Setting PTATLAS=ATLAS
		<class 'numpy.distutils.system_info.atlas_threads_info'>
		  NOT AVAILABLE

		atlas_info:
		<class 'numpy.distutils.system_info.atlas_info'>
		  NOT AVAILABLE

		c:\misc\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1532: UserWarning:
			Atlas (http://math-atlas.sourceforge.net/) libraries not found.
			Directories to search for the libraries can be specified in the
			numpy/distutils/site.cfg file (section [atlas]) or by setting
			the ATLAS environment variable.
		  warnings.warn(AtlasNotFoundError.__doc__)
		lapack_info:
		  libraries lapack not found in ['c:\\misc\\python\\python35-32\\lib', 'C:\\', 'c:\\misc\\python\\python35-32\\libs']
		  NOT AVAILABLE

		c:\misc\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1543: UserWarning:
			Lapack (http://www.netlib.org/lapack/) libraries not found.
			Directories to search for the libraries can be specified in the
			numpy/distutils/site.cfg file (section [lapack]) or by setting
			the LAPACK environment variable.
		  warnings.warn(LapackNotFoundError.__doc__)
		lapack_src_info:
		  NOT AVAILABLE

		c:\misc\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1546: UserWarning:
			Lapack (http://www.netlib.org/lapack/) sources not found.
			Directories to search for the sources can be specified in the
			numpy/distutils/site.cfg file (section [lapack_src]) or by setting
			the LAPACK_SRC environment variable.
		  warnings.warn(LapackSrcNotFoundError.__doc__)
		  NOT AVAILABLE

		Running from scipy source directory.
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "C:\Users\DANCE2~1\AppData\Local\Temp\pip-build-otq1zs_f\scipy\setup.py", line 415, in <module>
			setup_package()
		  File "C:\Users\DANCE2~1\AppData\Local\Temp\pip-build-otq1zs_f\scipy\setup.py", line 411, in setup_package
			setup(**metadata)
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
			config = configuration()
		  File "C:\Users\DANCE2~1\AppData\Local\Temp\pip-build-otq1zs_f\scipy\setup.py", line 335, in configuration
			config.add_subpackage('scipy')
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1000, in add_subpackage
			caller_level = 2)
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 969, in get_subpackage
			caller_level = caller_level + 1)
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 906, in _get_configuration_from_setup_py
			config = setup_module.configuration(*args)
		  File "scipy\setup.py", line 15, in configuration
			config.add_subpackage('linalg')
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1000, in add_subpackage
			caller_level = 2)
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 969, in get_subpackage
			caller_level = caller_level + 1)
		  File "c:\misc\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 906, in _get_configuration_from_setup_py
			config = setup_module.configuration(*args)
		  File "scipy\linalg\setup.py", line 20, in configuration
			raise NotFoundError('no lapack/blas resources found')
		numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

		----------------------------------------
	Command "c:\misc\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DANCE2~1\\AppData\\Local\\Temp\\pip-build-otq1zs_f\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DANCE2~1\AppData\Local\Temp\pip-ei4og5fl-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DANCE2~1\AppData\Local\Temp\pip-build-otq1zs_f\scipy\

**Comment by JohannesBuchner** [comment]
This is not a imagehash bug. pip in trying to install scipy, but fails. Try to install scipy. 
https://stackoverflow.com/questions/28190534/windows-scipy-install-no-lapack-blas-resources-found

**Comment by dance2die** [comment]
@JohannesBuchner Thank you, Johannes. I just started learning Python and wasn't sure what I was doing wrong. Thank you for your kind help by redirecting me to the useful link. I was able to install without a problem after installing Scipy.

	C:\Users\dance2die\Downloads>pip install scipy-0.18.1-cp35-cp35m-win32.whl
	Processing c:\users\dance2die\downloads\scipy-0.18.1-cp35-cp35m-win32.whl
	Installing collected packages: scipy
	Successfully installed scipy-0.18.1

	C:\Users\dance2die\Downloads>pip install ImageHash
	Collecting ImageHash
	  Using cached ImageHash-3.1.tar.gz
	Requirement already satisfied: numpy in c:\misc\python\python35-32\lib\site-packages (from ImageHash)
	Requirement already satisfied: scipy in c:\misc\python\python35-32\lib\site-packages (from ImageHash)
	Collecting pillow (from ImageHash)
	  Using cached Pillow-3.4.2-cp35-cp35m-win32.whl
	Collecting PyWavelets (from ImageHash)
	  Using cached PyWavelets-0.5.1-cp35-none-win32.whl
	Installing collected packages: pillow, PyWavelets, ImageHash
	  Running setup.py install for ImageHash ... done
	Successfully installed ImageHash-3.1 PyWavelets-0.5.1 pillow-3.4.2

**Comment by hemkumart** [comment]
OS: Windows 10
Python Version: 3.7
Pip Version: 19.0.3


I am getting following error message while trying to install (pip install chatterbot) .



`Command "c:\users\hem\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hem\\AppData\\Local\\Temp\\pip-install-f3q98400\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hem\AppData\Local\Temp\pip-record-rwylebu2\install-record.txt --single-version-externally-managed --prefix C:\Users\hem\AppData\Local\Temp\pip-build-env-9g3clkx8\overlay --compile" failed with error code 1 in C:\Users\hem\AppData\Local\Temp\pip-install-f3q98400\murmurhash\

  ----------------------------------------
Command "c:\users\hem\appdata\local\programs\python\python37-32\python.exe c:\users\hem\appdata\local\programs\python\python37-32\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\hem\AppData\Local\Temp\pip-build-env-9g3clkx8\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel>0.32.0.<0.33.0 Cython cymem>=2.0.2,<2.1.0 preshed>=2.0.1,<2.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.0.0.dev6" failed with error code 1 in None
`

**Comment by hemkumart** [comment]
anyone please help me in solving i am new to python

**Comment by JohannesBuchner** [comment]
Please post the full output.

**Comment by JohannesBuchner** [comment]
if you have an issue installing chatterbot, report it there https://github.com/gunthercox/ChatterBot
