### ISSUE TITLE
Note about Greyscale?

### ISSUE THREAD

**Issue by RONNCC** [JohannesBuchner/imagehash#42]
Would it be possible to add a note that it computes the hash on the greyscale rather than all 3/4 channels of an RGB/RGBA? -- I didn't realize that till later

**Comment by JohannesBuchner** [comment]
Sure, feel free to put it in where you would find it useful.

**Comment by JohannesBuchner** [comment]
Fixed with commit bce50d3

**Comment by RONNCC** [comment]
Thanks @JohannesBuchner  :)
