### ISSUE TITLE
What is 'six' in find_similar_images.py

### ISSUE THREAD

**Issue by kyle-pena-nlp** [JohannesBuchner/imagehash#43]
Shouldn't the line containing 'six' instead read 'images.iteritems()'?

**Comment by JohannesBuchner** [comment]
In Python 2, yes. https://pythonhosted.org/six/#six.iteritems

**Comment by kyle-pena-nlp** [comment]
My apologies, I am a noob.

**Comment by JohannesBuchner** [comment]
No worries, we all started there :)
