### ISSUE TITLE
Why intentionally shorten hash value of __hash__() of ImageHash class?

### ISSUE THREAD

**Issue by palmchou** [JohannesBuchner/imagehash#44]
It looks like the current implementation of \_\_hash__(): of ImageHash class divides the internal 64-bit hash value into several 8-bit values, then adds up the computed values from those 8-bit hash values.

The question is why doing so? It will make '0000ffff0000eeee' and 'ffff0000eeee0000' return the same hash value and lead to collision.
```
In [61]: hash(imagehash.hex_to_hash('0000ffff0000eeee'))
Out[61]: 986

In [62]: hash(imagehash.hex_to_hash('ffff0000eeee0000'))
Out[62]: 986
```

**Comment by JohannesBuchner** [comment]
hashes are not supposed to be unique, but for quickly assigning first buckets in e.g. dictionaries, for quick key search (first hash-bin, then linear search). For strings, an often used function is:

```
for c in some_string:
    hash = 101 * hash  +  ord(c)
```

We could do something similar with a small prime number. It remains to be demonstrated that this makes any difference (see the exhaustive discussion in #5 ).
