### ISSUE TITLE
Getting completely different hashes of almost identical images

### ISSUE THREAD

**Issue by SthPhoenix** [JohannesBuchner/imagehash#53]
Hi! I'm trying to compare image unmodified, as taken by camera, and photoshopped image (tweaked histogram and a bit changed white balance) and get distances above `25` if using code as in examples:
`hash = imagehash.phash(Image.open(path)) `

But if i modify code like this:
```
img = cv2.imread(path)
img = Image.fromarray(img)
hash = imagehash.phash(img)
```

I get distance of `0`
Looks like it might be caused by different color spaces, or something like that. 
Hope this info could help somebody.

**Comment by JohannesBuchner** [comment]
Hmm, strange. phash et al. should transform to grayscale inside. Could you attach an example case?

**Comment by SthPhoenix** [comment]
Image 1 - as taken, default color space AdobeRGB:
![_dsc0564](https://cloud.githubusercontent.com/assets/17834919/25771654/4aa9732c-3260-11e7-8370-8fcc62418677.JPG)

Image 2 - opened in photoshop and saved in sRGB:
![_dsc0564_ed3](https://cloud.githubusercontent.com/assets/17834919/25771702/55946cb4-3261-11e7-888b-cde1e0d68b3b.jpg)

Using `Image.open()` hashes are:
```
image1 = 1e2e4c3737160606
image2 = 52ed5d70716d6db1
```

Using `cv2.imread()`:
```
image1 = 72ed5c70616d6d31
image2 = 72eddc70616d6d31
```

**Comment by SthPhoenix** [comment]
Hm, after uploading photos, I've realized that original pic is not rotated by default, looks like `opencv ` handles rotation by itself. It was really hard to find, because all my viewers both on Windows and Ubuntu shown vertical images in both cases )

**Comment by JohannesBuchner** [comment]
Yes, perhaps it is related to various readers interpreting some headers differently.

**Comment by JohannesBuchner** [comment]
Downloading the images I can not reproduce the problem though. I use `from PIL import Image` with version 3.4.2.

**Comment by JohannesBuchner** [comment]
For both I get 2ddb5a24c7da3912. 
And with cv2 (2.4.13):
print imagehash.phash(PIL.Image.fromarray(cv2.imread('a.jpg')))
print imagehash.phash(PIL.Image.fromarray(cv2.imread('b.jpg')))
the same, 2ddb5a24c7da3912.

**Comment by SthPhoenix** [comment]
Sorry, accidentaly gave you dhashes, instead of phashes. Tried to download images from here and tested it again (phash):
PIL:
```
f91cb3cd44c39c98
2ddb5a34c7da3902
```
OpenCV:
```
2ddb5a34c6fa3902
2ddb5a34c6fa3902

```
That's wierd, not only problem stays, but hashes are also slightly different from yours

**Comment by Hyperclaw79** [comment]
Any updates on this one? I am facing a similar issue with two different size images taken from the internet using `requests` module, converting them into `BytesIO` object and then to PIL Image Object using `Image.Open()` and then hashing them.

```py
>>> import requests
>>> from PIL import Image
>>> import imagehash
>>> sess = requests.Session()
>>> from io import BytesIO

>>> def gen_bytesIo(url):
...     im_dat = sess.get(url).content
...     return BytesIO(im_dat)
...
>>> def hasher(bytesIO_obj):
...     ahash = str(imagehash.average_hash(Image.open(bytesIO_obj)))
...     dhash = str(imagehash.dhash(Image.open(bytesIO_obj)))
...     phash = str(imagehash.phash(Image.open(bytesIO_obj)))
...     whash = str(imagehash.whash(Image.open(bytesIO_obj)))
...     return {'ahash': ahash, 'dhash': dhash, 'phash': phash, 'whash': whash}
...
>>> print(hasher(gen_bytesIo('https://www.pokecord.com/assets/lUUbmdNYWQGe.png')))
{'ahash': 'db006f131990e0ff', 'dhash': '33aeccb2d3270a1b', 'phash': 'a914db48a9e596b3', 'whash': 'ff026f031190e0ff'}
>>> print(hasher(gen_bytesIo('https://cdn.discordapp.com/attachments/408321293960871956/456783325995073577/PokecordSpawn.jpg')))
{'ahash': '0050f0f878f2f140', 'dhash': '10a084b290268388', 'phash': 'c01a329d19e777c3', 'whash': '8070f0f8fcfaf340'}
```

**Comment by JohannesBuchner** [comment]
@Hyperclaw79 
You can look at hash.hash to see where in the image the difference is.
They have slightly different outlines, not sure if that is enough to trigger the difference.

**Comment by Hyperclaw79** [comment]
@JohannesBuchner As you suggested, I've tried printing out `hash.hash` to see the differences but I am not able to proceed using that info.

```py
https://cdn.discordapp.com/attachments/408321293960871956/459713247415894016/PokecordSpawn.jpg:
[[False  True False  True  True False  True False]
 [ True  True  True False False  True False False]
 [ True False  True False False  True False False]
 [ True False False False  True  True False False]
 [ True  True  True False  True  True False False]
 [False  True  True False False False  True False]
 [ True  True  True  True False False False False]
 [ True False  True  True False False False False]]

https://www.pokecord.com/assets/sSchDWVBILou.png:
[[ True  True False  True  True False  True  True]
 [ True  True  True False False  True  True False]
 [ True False  True False False  True False False]
 [ True False False False  True  True False False]
 [ True  True  True False  True  True False False]
 [False  True  True False False False  True False]
 [ True False  True  True False False False False]
 [False False  True  True False False  True  True]]
```
Even though the images look visually similar to the naked eye, they are getting hashed differently. Any way for me to use the `hash.hash` information to fix the detection?

**Comment by JohannesBuchner** [comment]
Is this ahash?

**Comment by JohannesBuchner** [comment]
So in the left half, only the top left pixel (of a 8x8 grayscaled version) is different. 
IIRC, ahash reports which pixels are above or below the average intensity. Maybe one image is slightly brighter than the other (in some parts), and that shifted the average?

**Comment by Hyperclaw79** [comment]
> Is this ahash?

Nope, it is dhash.

> So in the left half, only the top left pixel

Yea that's what I inferred from the hashes.

> Maybe one image is slightly brighter than the other (in some parts), and that shifted the average

Interesting guess. Tough to see that with the naked eye.

Is there a way to set the ROI for the images or something? I haven't worked much on Image Processing, so I've no clue. 😅

**Comment by JohannesBuchner** [comment]
OK, can you also post dhash.hash * 1, it should be easier to interpret

**Comment by JohannesBuchner** [comment]
![testl](https://user-images.githubusercontent.com/51015/41795912-c1ff3d82-7664-11e8-83f2-22e40cacf80c.jpg) ![testl2](https://user-images.githubusercontent.com/51015/41795914-c2464588-7664-11e8-9dd2-0c39ffedfb0e.jpg)

If you flip between them, one has several bright spots. That might have to do with the transparency. You could try putting a white background, transform to RGB (without alpha channel), and see if it makes a difference.

With hash1 - hash2 you can compute the hamming distance. For your application, you might want to live with a threshold > 0.
