### ISSUE TITLE
Add an __int__() function

### ISSUE THREAD

**Issue by wonkodv** [JohannesBuchner/imagehash#55]
I need to access the imagehash as an integer to store it in a database and would like to say `int(imageHash)` without converting to string and then back to int.

**Comment by JohannesBuchner** [comment]
Patches are welcome. Otherwise you can also access the numpy array with .hash and convert that to a single integer (or blob) in a way that suits your database.

**Comment by wonkodv** [comment]
I added an int method, but it is not backwards compatible.
e615ef07f4a61adda5d54b586ce02194ccb19cfd

I changed the string method to use that int which makes str faster.

The old hash to string function has the most significant bit from the top right corenr, mine has bottom right.

pick whatever you feel like.

**Comment by wonkodv** [comment]
that int is also perfekt as  __hash__ (#44)

**Comment by JohannesBuchner** [comment]
Hmm, could we make a new class ImageIntHash, which is int-based? Then we are backwards-compatible and we only need a ImageHash-to-ImageIntHash function.

**Comment by wonkodv** [comment]
I think i have it, 06ac31996c5b46545614964610cbbcfbcbccdac5 only one `reversed` was missing.

**Comment by JohannesBuchner** [comment]
If this is still of interest, please open a PR so that the CI can run on it.

**Comment by oliveskur** [comment]
Why does ImageHash prefer a hex string to an integer? Is it easier and faster than an integer?
I can convert a hex string to an integer, but I don't know if this is the most optimal way:
phash = int(str(imagehash.phash(img)),16)

**Comment by JohannesBuchner** [comment]
It is intended for storage in databases, and as a fixed length printable identifier. You can access the individual integers with .hash.

**Comment by oliveskur** [comment]
An integer is better suited for storage in databases - a hex string is 16 bytes long, but the integer from this string is only 8 bytes long - less storage space and faster search. Hex is just a human-readable binary format. Method .hash. returns an array of booleans (bytes by bits). Converting a hex string to an integer is faster than converting a boolean array to an integer in Python, so .hash. is beyond my interest.

**Comment by JohannesBuchner** [comment]
@oliveskur maybe you can test https://github.com/JohannesBuchner/imagehash/pull/222 , does storing it in databases work for you, is the hash recoverable cross-platform (endianness)?
