### ISSUE TITLE
Identifies similar images in the directory.

### ISSUE THREAD

**Issue by vap31** [JohannesBuchner/imagehash#59]
Hi, I am new to ML coding. Can you please suggest me ,which parameter i need to fill to get output. I have two images 1.jpg and 2.jpg. I want to find similarity between them. How shall i do it? I  would be greatful . Thanks

`  def usage():
        sys.stderr.write("""SYNOPSIS: %s [ahash|phash|dhash|...] [<directory>]
Identifies similar images in the directory.
Method: 
  ahash:      Average hash
  phash:      Perceptual hash
  dhash:      Difference hash
  whash-haar: Haar wavelet hash
  whash-db4:  Daubechies wavelet hash
(C) Johannes Buchner, 2013-2017
""" % sys.argv[0])
        sys.exit(1)'

**Comment by JohannesBuchner** [comment]
Have a look at the README file, under "Basic usage"
https://github.com/JohannesBuchner/imagehash#basic-usage

**Comment by wamm0909** [comment]
> Hi, I am new to ML coding. Can you please suggest me ,which parameter i need to fill to get output. I have two images 1.jpg and 2.jpg. I want to find similarity between them. How shall i do it? I would be greatful . Thanks
> 
> ` def usage():
> sys.stderr.write("""SYNOPSIS: %s [ahash|phash|dhash|...] []
> Identifies similar images in the directory.
> Method:
> ahash: Average hash
> phash: Perceptual hash
> dhash: Difference hash
> whash-haar: Haar wavelet hash
> whash-db4: Daubechies wavelet hash
> (C) Johannes Buchner, 2013-2017
> """ % sys.argv[0])
> sys.exit(1)'

I have the same question，do you solve it？please tell me，thanks

**Comment by JohannesBuchner** [comment]
@wamm0909 see https://github.com/JohannesBuchner/imagehash/issues/59#issuecomment-313451867
