### ISSUE TITLE
How to get the mean or average of a set of hashes?

### ISSUE THREAD

**Issue by remibolcom** [JohannesBuchner/imagehash#60]
Suppose I have a list of 100 imagehashes. How do I find the hash that is in the center of this high-dimensional cloud? I am looking for a way to find the mean or average of a set of hashes.

**Comment by JohannesBuchner** [comment]
Get the hash as a sequence of numbers, define a metric (e.g. euclidean, mahalanobis or standardised euclidean), compute the mean, compute for each the distance to the mean and select the nearest.

**Comment by remibolcom** [comment]
> Get the hash as a sequence of numbers

How?

**Comment by JohannesBuchner** [comment]
`value = myhash.hash.flatten()`
should give you a numpy int array.
