### ISSUE TITLE
imagehash from memory object saves corrupted file

### ISSUE THREAD

**Issue by elocio** [JohannesBuchner/imagehash#62]
When I run imagehash against an upload that exists in memory but has not yet been written to disk, the resulting file is corrupted after disk write. For example:

`f = form.image.data`
`filename = secure_filename(f.filename)`
`imghash = imagehash.dhash(Image.open(f))`
`f.save(os.path.join(imgdir, filename))`

The saved file is missing bytes and isn't a valid image.

If I run imagehash against an existing file on disk, it works as expected. I would like to check the hash against a db record before writing anything to disk however.

I have also tested simply opening the image using PIL's `Image.open()` to make sure that wasn't trashing the file, but it successfully writes the image to disk afterwards. It is only after running imagehash against the PIL-opened file that I lose bytes and write an incomplete file to disk.

Is this a bug or am I missing something here?

I'm using Pillow (4.2.1) and ImageHash (3.4). This is a Flask (0.12.2) site where the uploaded file is wrapped in the Werkzeug FileStorage class.

**Comment by JohannesBuchner** [comment]
Your example code does not seem to depend on imagehash. If it still fails with:

```
f = form.image.data
filename = secure_filename(f.filename)
img = Image.open(f)
f.save(os.path.join(imgdir, filename))
```

please constact the relevant libraries. I don't see how imagehash could be involved here, because it does not do any i/o nor modifies PIL/pillow bytes.

**Comment by elocio** [comment]
As I mentioned, I did test a simple `Image.open` call as you show in your example:

```
f = form.image.data
filename = secure_filename(f.filename)
img = Image.open(f)
f.save(os.path.join(imgdir, filename))
```
and the resulting saved file is OK.

However, when insert imagehash as shown here:
```
f = form.image.data
filename = secure_filename(f.filename)
imghash = imagehash.dhash(Image.open(f))
f.save(os.path.join(imgdir, filename))
```
the resulting file is missing bytes and is not a valid image file.

**Comment by JohannesBuchner** [comment]
How about:

`
f = form.image.data
filename = secure_filename(f.filename)
image = Image.open(f)
image = image.convert("L").resize((hash_size + 1, hash_size), Image.ANTIALIAS)
pixels = numpy.array(image.getdata(), dtype=numpy.float).reshape((hash_size, hash_size + 1))
f.save(os.path.join(imgdir, filename))
`

Then try to simplify by removing either of the two long lines, or simplifying them.

**Comment by JohannesBuchner** [comment]
You can also try `Image.open(f, mode='r')`

**Comment by elocio** [comment]
`image = image.convert("L").resize((hash_size + 1, hash_size), Image.ANTIALIAS)`

fails with:

`NameError: name 'hash_size' is not defined`

I import:
```
from PIL import Image
import imagehash
```

**Comment by JohannesBuchner** [comment]
set it to 8

**Comment by elocio** [comment]
BTW I also tried:
```
f = form.image.data
filename = secure_filename(f.filename)
image = Image.open(f, mode='r')
imghash = imagehash.dhash(image)
f.save(os.path.join(imgdir, filename))
```
but the file save is also no good:

```
original_file: 4622336 bytes
saved_file: 886784 bytes
```

**Comment by JohannesBuchner** [comment]
This page: https://stackoverflow.com/questions/29367990/what-is-the-difference-between-image-resize-and-image-thumbnail-in-pillow-python
points to Image.resize being the culprit, resizing in-place.

So this code should also trigger the problem:

```
f = form.image.data
filename = secure_filename(f.filename)
image = Image.open(f).resize((9, 8))
f.save(os.path.join(imgdir, filename))
```

Perhaps making a copy of the PIL object can resolve this?

```
f = form.image.data
filename = secure_filename(f.filename)
img = Image.open(f).copy()
imghash = imagehash.dhash(img)
f.save(os.path.join(imgdir, filename))
```

**Comment by elocio** [comment]
I tried:
```
from PIL import Image
import imagehash
import numpy

f = form.image.data
filename = secure_filename(f.filename)
image = Image.open(f)
image = image.convert("L").resize((8 + 1, 8), Image.ANTIALIAS)
pixels = numpy.array(image.getdata(), dtype=numpy.float).reshape((8, 8 + 1))
f.save(os.path.join(imgdir, filename))
```
but results are the same:
```
original_file: 4622336 bytes
saved_file:     886784 bytes
```

Somehow the file is getting truncated...

**Comment by JohannesBuchner** [comment]
Note that that last code you tried there does not depend on imagehash.

**Comment by elocio** [comment]
Ok, I'll dig deeper into PIL/numpy file handling. Thanks for your help and the quick responses.

**Comment by JohannesBuchner** [comment]
Good. I hope you didn't overlook https://github.com/JohannesBuchner/imagehash/issues/62#issuecomment-327025287 which makes me suspect Image.resize.

**Comment by elocio** [comment]
Thanks, I had indeed overlooked https://github.com/JohannesBuchner/imagehash/issues/62#issuecomment-327025287, though it looks like it's actually `Image.thumbnail` that resizes in place : [http://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.Image.thumbnail](url)

FWIW, I also tried making a copy of the PIL object as you suggested, but the results are the same. Pretty bizzare...

I'll post the solution here for posterity when I have working code.

**Comment by elocio** [comment]
Well after much fiddling around, the explanation turns out to be quite simple. When opening the file with PIL `Image.open(f)` the file pointer is advanced but not reset before writing the file. I would think that in this case the file pointer would reach the end of the file and no bytes would be written, but it doesn't seem so based on my previous partial writes. In any case, the solution is to rewind the file pointer to the start of the file before saving:
```
f.seek(0)
f.save(os.path.join(imgdir, filename))
```
