### ISSUE TITLE
Which alternative is best?

### ISSUE THREAD

**Issue by sibe7691** [JohannesBuchner/imagehash#67]
Which hash function would be best to use if I compare a photo from my phone to a set of photos stored in a catalog on my computer?

Im trying to achieve basic image-searching.

**Comment by JohannesBuchner** [comment]
Good question. If you do not have any preferences, maybe start with phash and an hash size of 8 (the default).

I guess at some point someone should do a proper comparison of the algorithms and their parameters for different types of images. But I guess there are different metrics one might optimize for (speed, hash size, false and true collision rates, ...).

**Comment by colegleason** [comment]
@JohannesBuchner do you have intuition on which algorithm will be fastest?

**Comment by JohannesBuchner** [comment]
Should be average_hash just based on simplicity of its operations.

**Comment by filipemansano** [comment]
https://content-blockchain.org/research/testing-different-image-hash-functions/

**Comment by JohannesBuchner** [comment]
Thanks @filipemansano , that is really interesting!
