### ISSUE TITLE
Image similarity for  million images

### ISSUE THREAD

**Issue by vijaysagi** [JohannesBuchner/imagehash#68]
Hi all,
using the below code, i tried with several images to find the similarity  but the difference between the hashvalues  are not matching

hash = imagehash.phash(Image.open(1.jpg'))
otherhash = imagehash.phash(Image.open('2.jpg'))
print(hash == otherhash)
print(hash-otherhash)

please suggest how can i get the similarity.

please suggest how can we search million images  in the database based on the hashvalue

Thanks
vijay

**Comment by JohannesBuchner** [comment]
What output do you get?

**Comment by vijaysagi** [comment]
The following is the output of same person(1.jpg & 2.jpg) and two hashes generated are not similar
hash:  adf930b4d082cfc3
otherhash: ea5ce3e187098e9c

print(hash == otherhash)
output::  False
print(hash-otherhash)
output: 34

pls suggest
FYI 
images used:
![1](https://user-images.githubusercontent.com/6347404/35956094-8ca0b342-0cb9-11e8-82ac-a24250ec12fa.jpg)
![2](https://user-images.githubusercontent.com/6347404/35956095-8cdd252a-0cb9-11e8-9814-99b324343a2c.jpg)

**Comment by JohannesBuchner** [comment]
Please spend some time understanding what these hashes do: https://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html

They are mostly meant for having the same image but with different coloring, contrast, small shifts, etc. 
Likely the background steps and shirt color make the hashes different. Keep in mind that the algorithm does not have a concept of a person, only pixels.
