### ISSUE TITLE
Why using median instead of average in phash?

### ISSUE THREAD

**Issue by chenzd91** [JohannesBuchner/imagehash#70]
Average value is used after dct in phash_simple, whereas in phash, median is used. Why?
I found that using average will produce more similar hash values for similar images.

**Comment by JohannesBuchner** [comment]
Interesting that you find it to work better. There are some more difference between the two functions -- the dct is taken twice in phash, only once in phash_simple.

**Comment by chenzd91** [comment]
So why take 2 dct in phash? Is there any theory behind this?

**Comment by JohannesBuchner** [comment]
The dct function only works in one direction. According to the blog I based this off, I think they wanted a 2d DCT, so the function has to be called twice. 

As I understand it, there is no substantial theory behind any of the hash functions, people just come up with methods that seem to work for them. There are some other algorithms implemented here http://www.cs.huji.ac.il/~yweiss/SpectralHashing/ http://www.stonehenge.com/merlyn/LinuxMag/col50.html http://phash.org/

It would be interesting to test a bit more systematically the different hashes (and their parameters, e.g. hash size) -- but I am not sure how one would define one hash method to work better than another hash method. 

One approach could be taking a very large sample and finding the union of hash collisions across multiple methods, then classifying these manually as different or same. Then, the fraction of true and false positive hash collisions of each algorithm can be evaluated.

Another option would be to define various transforms (shifts, crops, rotations, watermarking, adding frames, hue-saturation-brightness changes, various instagram filters) and measure the amount of transformation until the hash changes.
