### ISSUE TITLE
Tag a 4.0 release

### ISSUE THREAD

**Issue by bjlittle** [JohannesBuchner/imagehash#72]
@JohannesBuchner Just for completeness, would it be possible to tag a `4.0` release?

The `imagehash` [recipe](https://github.com/conda-forge/imagehash-feedstock/blob/master/recipe/meta.yaml) on `conda-forge` avoids this as it pulls it's source from PyPI.

Thanks.

**Comment by JohannesBuchner** [comment]
done.

**Comment by bjlittle** [comment]
Awesome, thanks :smiley:
