### ISSUE TITLE
Why I use the function about compute hash when two pictures have different sizes but similar.

### ISSUE THREAD

**Issue by F1And** [JohannesBuchner/imagehash#73]
I know your function will resize a picture default **8*8** or **8*4** or **8*9** when it compute the HASH. But when I have two pictures that so similar but have different size. The two pictures' **Hamming_distance** is too big. My function is this:
```python
def Hamming_distance(hash1, hash2):
        """
        :param hash1: hash1
        :param hash2: hash2
        :return: distance
        """
        distance = 0
        try:
            for index in range(len(hash1)):
                if hash1[index] != hash2[index]:
                    distance += 1
            return distance
        except Exception, e:
            logging.error('hamming distance fail %s', e)
```
Please tell me how can I do?

**Comment by JohannesBuchner** [comment]
If you have two very similar pictures of different size, the hash should be the same.

Are you saying you have two hashes that are of different size and and want to compare them nevertheless?

Maybe you can give an example input and output and what you expected instead.

**Comment by F1And** [comment]
**For example, I have two pictures like this**:

![7_Verify.jpg](https://upload-images.jianshu.io/upload_images/2955280-e056e3ee33a9cdee.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
The first picture's hash is `cc4c66be99516e54`.I use the function `phash` default resize`8*9`.

![7_Template.jpg](https://upload-images.jianshu.io/upload_images/2955280-d9d9a59c75d33bc7.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
The second picture's hash is `cc4c3699556699b9`.I use the function `phash` default resize `8*9`.

But the distance about two pictures is 11. I think two pictures is very similar, and we change the picture with Gary.I have no idea to improve the hash. Please help me.

**Comment by alecz20** [comment]
I'm curious if `dhash` gives a lower hamming distance.

**Comment by F1And** [comment]
I try to use `dhash`. The distance is **12** more than `phash`. So I don't konw how can I do.

**Comment by JohannesBuchner** [comment]
You can look at the hash.hash array to see in which area the differences are.

I am reuploading your examples, scaled to 64x64px and grayscaled. You can see there that they are different:
![a](https://user-images.githubusercontent.com/51015/41047451-9f2465f4-697a-11e8-98d2-9fcc406b8bd6.png)
![b](https://user-images.githubusercontent.com/51015/41047462-a1ad9390-697a-11e8-906f-3f72e8e8f063.png)

These hashes are not invariant to shifts and cut-outs.
If you need these images to be the same, you can try using various transforms, and computing each hash. Then, to compare between images, look for the smallest difference between any pair of hashes.
Transforms could be cutting out 20% from the various sides, or selecting the largest possible square (there should be two solutions).

**Comment by F1And** [comment]
Thanks for your help.I maybe have a way to improve my code.

**Comment by F1And** [comment]
Thanks for answer the problem. I ‘ll close the question.
