### ISSUE TITLE
No need to pad HEX

### ISSUE THREAD

**Issue by renedlog** [JohannesBuchner/imagehash#74]
Why do you pad the conversion with zeros?
There is no need to do this. 
`binary_array = '{:0>{width}b}'.format(int(hexstr, 16), width = hash_size * hash_size)`
to get rid of 0b like:
`bin(int('3838b59d0c1c7fd8', 16))`

just do
`'{:b}'.format(int('3838b59d0c1c7fd8', 16), width = hash_size * hash_size)`

or
`format((int('3838b59d0c1c7fd8', 16)),'08b')`

**Comment by JohannesBuchner** [comment]
This is done because when you reverse back to an ImageHash object, you would not know how large the hash was.
