### ISSUE TITLE
Rule of thumb Threshold for phash

### ISSUE THREAD

**Issue by jebrage** [JohannesBuchner/imagehash#76]
What would be an ideal value to use as a threshold for phash? This [blog](https://tech.okcupid.com/evaluating-perceptual-image-hashes-okcupid/) here did some research on it. However, I couldn't make out much from it.  Especially as it didn't provide any conclusive threshold value. I'm fairly new to this and a rule of thumb threshold might benefit newcomers

**Comment by odedkalev** [comment]
It all depends on your data, check the diff between your images and see how low does the threshold needs to be in order to avoid collision

**Comment by JohannesBuchner** [comment]
I put some more links in the readme and am closing this bug.
