### ISSUE TITLE
`whash` sometimes gives invalid results

### ISSUE THREAD

**Issue by john-parton** [JohannesBuchner/imagehash#82]
I frequently see this hash when doing a `whash`: `ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`

Visually inspecting the images, they are not at all similar. Here are two images:

![test1](https://user-images.githubusercontent.com/2071543/49091457-87bfb600-f225-11e8-8c64-554a137baa94.png)
![test2](https://user-images.githubusercontent.com/2071543/49091458-87bfb600-f225-11e8-9984-4e1852d9da58.png)

Here's my test code:

```python
import os

import imagehash
from PIL import Image


class ImageHasher(object):

    HASH_SIZE = 32
    IMAGE_SCALE = 2048

    def __call__(self, f):

        image = Image.open(f)

        hash_ = imagehash.whash(
            image,
            hash_size=self.HASH_SIZE,
            image_scale=self.IMAGE_SCALE
        )

        return str(hash_)


image_hasher = ImageHasher()

def main():
    for filename in os.listdir('images'):
        path = os.path.join('images', filename)
        with open(path, 'rb') as f:
             print(image_hasher(f))


main()
```

Any clues as to what's going on?

Thanks.

**Comment by JohannesBuchner** [comment]
Both hashes are that value?

**Comment by john-parton** [comment]
Yes.

**Comment by JohannesBuchner** [comment]
Hmm. No idea. You'd have to execute whash step by step.

**Comment by JohannesBuchner** [comment]
The issue is that your images have a large (and similar) white borders. 

You can try to autocrop them first.

This gives me different whashes.
