### ISSUE TITLE
Flipping an image doesn't flip the hash (phash, dhash)

### ISSUE THREAD

**Issue by HatScripts** [JohannesBuchner/imagehash#84]
For example, with this image originally and flipped horizontally as input:
![input](https://user-images.githubusercontent.com/5691865/50373112-ed893d00-062d-11e9-8090-97d4b6bad6ef.png)
`average_hash` outputs hashes that satisfyingly look like this (`#` = 1, `.` = 0):
![output_average_hash](https://user-images.githubusercontent.com/5691865/50373118-085bb180-062e-11e9-80e9-58e4ed2b7961.png)
While `phash` outputs hashes that look this. When shown side-by-side like this I would expect them to be symmetrical.
![output_phash](https://user-images.githubusercontent.com/5691865/50373125-29bc9d80-062e-11e9-92fd-11bb853bf704.png)

I'm assuming this a bug? If not, could you please explain this behaviour? I find it quite strange.

* **average_hash** - valid
* **dhash_vertical** - valid
* **whash** - valid
* **phash** - invalid
* **phash_simple** - invalid
* **dhash** - invalid

Here's a minimal example:
```py
import numpy as np
from imagehash import *

def hash_to_text(a):
    return "\n".join(" ".join(("#" if x else ".") for x in y) for y in a)

im_orig = Image.open("samples/lion.jpg")
im_horz = im_orig.transpose(Image.FLIP_LEFT_RIGHT) 

for func in (average_hash, phash, phash_simple, dhash, dhash_vertical, whash):
    hash_orig = func(im_orig).hash
    hash_horz = func(im_horz).hash
    name = func.__name__
    print("==", name, "==")
    if np.all(hash_orig == np.fliplr(hash_horz)):
        print("CORRECT RESULT")
    else:
        print(name + "(im_orig).hash:\n" +
              hash_to_text(hash_orig))
        print("np.fliplr(" + name + "(im_horz).hash):\n" +
              hash_to_text(np.fliplr(hash_horz)))
```

**Comment by JohnTravolski** [comment]
Was this ever solved?

**Comment by JohannesBuchner** [comment]
This is not a bug, just the way phash and dhash work. Only in ahash the hash has a pixel image meaning. In phash, the first column/row have a special purpose, that is why it is not symmetric upon flipping.
