### ISSUE TITLE
AttributeError: 'str' object has no attribute 'convert

### ISSUE THREAD

**Issue by minou30** [JohannesBuchner/imagehash#87]
Python error message on  imagehash.average_hash(i) call:

image = image.convert("L").resize((hash_size, hash_size), Image.ANTIALIAS)
AttributeError: 'str' object has no attribute 'convert'

(OpenCV 4.0, Python 3.7 with "
from PIL import Image
import imagehash
" in script)

**Comment by minou30** [comment]
The issue arises when passing an opencv image object to the hash functions.

How to convert an opencv image object to the image type required by the imagehash hash functions?  (The files are local so do not need to be requested from a URL.)

**Comment by JohannesBuchner** [comment]
You need to pass a PIL object, not a URL/filename.

**Comment by JohannesBuchner** [comment]
https://stackoverflow.com/questions/13576161/convert-opencv-image-into-pil-image-in-python-for-use-with-zbar-library

**Comment by JohannesBuchner** [comment]
I am closing this, but #78 may be of interest for you.
