### ISSUE TITLE
Need ImageHash.__lt__ for sorting the hashes :)

### ISSUE THREAD

**Issue by archtaurus** [JohannesBuchner/imagehash#92]
Please add ImageHash.__lt__ method

**Comment by JohannesBuchner** [comment]
What order would you like hashes to have?

**Comment by archtaurus** [comment]
like so 发自我的华为手机-------- 原始邮件 --------主题：Re: [JohannesBuchner/imagehash] Need ImageHash.__lt__ for sorting the hashes :) (#92)发件人：Johannes Buchner 收件人：JohannesBuchner/imagehash 抄送：Zhao Xin <7176466@qq.com>,Author What order would you like hashes to have?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JohannesBuchner/imagehash/issues/92?email_source=notifications\u0026email_token=AAJU3LB4MXNMOB7UN5HHCI3QFJOTTA5CNFSM4IM2XSR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4SGTNA#issuecomment-522480052",
"url": "https://github.com/JohannesBuchner/imagehash/issues/92?email_source=notifications\u0026email_token=AAJU3LB4MXNMOB7UN5HHCI3QFJOTTA5CNFSM4IM2XSR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4SGTNA#issuecomment-522480052",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by archtaurus** [comment]
Could you see those pictures in email?

**Comment by archtaurus** [comment]
```
zhaoxin at lanchou in ~/Working/batget on master [!?]
$ .venv/bin/python imagehash.py 
bfbfdf9fcf810080 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_03.jpg
ffffff00008fffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_03.jpg
ffffff0000ffffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_02.jpg
ffff81000081ffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_04.jpg
ffc781818181c1ff /home/zhaoxin/Working/batget/tmp/test_images/59107081758002080700448799528301782277_01.jpg
bf9f9f8fc7808101 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_04.jpg
bf9f9f8f878181c1 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_02.jpg
ffe1818181c1c1ef /home/zhaoxin/Working/batget/tmp/test_images/59107081758002080700448799528301782277_03.jpg
========================================
bf9f9f8f878181c1 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_02.jpg
bf9f9f8fc7808101 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_04.jpg
bfbfdf9fcf810080 /home/zhaoxin/Working/batget/tmp/test_images/147826880669145728878773725465315383436_03.jpg
ffc781818181c1ff /home/zhaoxin/Working/batget/tmp/test_images/59107081758002080700448799528301782277_01.jpg
ffe1818181c1c1ef /home/zhaoxin/Working/batget/tmp/test_images/59107081758002080700448799528301782277_03.jpg
ffff81000081ffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_04.jpg
ffffff00008fffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_03.jpg
ffffff0000ffffff /home/zhaoxin/Working/batget/tmp/test_images/293313817038284108156920858523196074759_02.jpg
zhaoxin at lanchou in ~/Working/batget on master [!?]

```

**Comment by archtaurus** [comment]
```python
class ImageHash(object):

    def __lt__(self, other):
        return int(str(other), 16) - int(str(self), 16) > 0
```

**Comment by archtaurus** [comment]
```python
import random
import glob
from PIL import Image
jpgs = glob.glob('/home/zhaoxin/Working/batget/tmp/test_images/*.jpg')
result = []
random.shuffle(jpgs)
for i in jpgs:
    with open(i, 'rb') as f:
        j = Image.open(f)
        hash = average_hash(j)
        print(hash, i)
        result.append((hash, i))
print('='*40)
for i, j in sorted(result):
    print(str(i), j)
```

**Comment by JohannesBuchner** [comment]
I would suggest you enhance the ImageHash object with a subclass:
```
from imagehash import ImageHash
class SortableImageHash(ImageHash):

    def __lt__(self, other):
        return int(str(other), 16) - int(str(self), 16) > 0`
```

**Comment by JohannesBuchner** [comment]
I suspect you do not actually need them sorted, you just want duplicates to be next to each other? In that case, use a hashmap with a list.

```
import random
import glob
from collections import defaultdict
from PIL import Image
jpgs = glob.glob('/home/zhaoxin/Working/batget/tmp/test_images/*.jpg')
result = defaultdict([])
for filename in jpgs:
    with open(filename, 'rb') as f:
        j = Image.open(f)
        hash = average_hash(j)
        print(hash, filename)
        result[hash].append(filename)
print('='*40)
for hash, filename in result.items():
    print(str(hash), filename)
```

**Comment by archtaurus** [comment]
thank you for your advice.发自我的华为手机-------- 原始邮件 --------主题：Re: [JohannesBuchner/imagehash] Need ImageHash.__lt__ for sorting the hashes :) (#92)发件人：Johannes Buchner 收件人：JohannesBuchner/imagehash 抄送：Zhao Xin <7176466@qq.com>,Author I suspect you do not actually need them sorted, you just want duplicates to be next to each other? In that case, use a hashmap with a list.
import random
import glob
from collections import defaultdict
from PIL import Image
jpgs = glob.glob('/home/zhaoxin/Working/batget/tmp/test_images/*.jpg')
result = defaultdict([])
for filename in jpgs:
    with open(filename, 'rb') as f:
        j = Image.open(f)
        hash = average_hash(j)
        print(hash, filename)
        result[hash].append(filename)
print('='*40)
for hash, filename in result.items():
    print(str(hash), filename)


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JohannesBuchner/imagehash/issues/92?email_source=notifications\u0026email_token=AAJU3LFHP6G7ZRNTA4WK343QFOT53A5CNFSM4IM2XSR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4VQNNQ#issuecomment-522913462",
"url": "https://github.com/JohannesBuchner/imagehash/issues/92?email_source=notifications\u0026email_token=AAJU3LFHP6G7ZRNTA4WK343QFOT53A5CNFSM4IM2XSR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4VQNNQ#issuecomment-522913462",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
