### ISSUE TITLE
imagehash.average_hash results in array instead of string

### ISSUE THREAD

**Issue by k0fi** [JohannesBuchner/imagehash#93]
Using python 2.7, when I try:

       `from PIL import Image 
       import imagehash
       img = Image.open(path)
       hash = imagehash.average_hash(img)
        print ("hash is:", hash)`

The result is an array like this:

`('hash is:', array([[False, False, False,  True, False, False,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  False,  True, False, False],
       [False,  True,  True,  True,  True,  True,  True, False],
       [False, False,  True, False, False, False,  True, False],
       [False, False, False, False, False, False,  True,  True]])`

Instead of a string. What I'm missing here? How can I fix it?

**Comment by JohannesBuchner** [comment]
`print "hash is: %s" % hash` should work

**Comment by k0fi** [comment]
@JohannesBuchner  how can I save it to a string variable?

**Comment by JohannesBuchner** [comment]
You can make a string with `s = str(hash)`. 

To compare distances, see https://github.com/JohannesBuchner/imagehash#basic-usage

**Comment by k0fi** [comment]
Thansk for the tip, but when I convert hash to string I can not calcuate the distance:

       `s = str(imagehash.average_hash(im0))
        print "s is:%s" % s`

gives:
`s is:078000c3cfcf8f8f`

But then 
     `distance = s - 94b1b9fcfcfcf0f0`

results in:

`unsupported operand type(s) for -: 'str' and 'str'`

How can I fix this?

**Comment by step21** [comment]
convert it back?

**Comment by k0fi** [comment]
@step21 
I'd like to calculate the distance. Please elaborate your answer with code.

**Comment by step21** [comment]
well if we look at https://github.com/JohannesBuchner/imagehash/blob/master/imagehash/__init__.py we find `def hex_to_hash(hexstr)` which takes a string and gives you a hash object. Then you should be able to compute the distance as normal, afaik.

**Comment by JohannesBuchner** [comment]
@k0fi: What gave you the idea that you need to convert to a string first, when you already have the ImageHash object?

**Comment by k0fi** [comment]
Well, I wanted to use `imagehash.average_hash(img)` to compare distances.Bbut when I printed it out, to my surprise it gave me an array of Boolean lists, as you can see above. Hence the question.

**Comment by JohannesBuchner** [comment]
So does this from the readme not work for you?
```
>>> import imagehash
>>> hash = imagehash.average_hash(Image.open('test.png'))
>>> otherhash = imagehash.average_hash(Image.open('other.bmp'))
>>> is_same = hash == otherhash
>>> distance = hash - otherhash
```
