### ISSUE TITLE
Python version >= 3.5 required ?

### ISSUE THREAD

**Issue by k0fi** [JohannesBuchner/imagehash#94]
I can not install  ImageHash on my legacy environment which uses `Python 2.7.9`

```
`$pip install ImageHash
Downloading/unpacking ImageHash
  Downloading ImageHash-4.0-py2.py3-none-any.whl (295kB): 295kB downloaded
Downloading/unpacking numpy (from ImageHash)
  Downloading numpy-1.17.0.zip (6.5MB): 6.5MB downloaded
  Running setup.py (path:/tmp/pip-build-wySIh5/numpy/setup.py) egg_info for package numpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-wySIh5/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-wySIh5/numpy/setup.py", line 31, in <module>

    raise RuntimeError("Python version >= 3.5 required.")

RuntimeError: Python version >= 3.5 required.`
```

However, I could install it on my other machine running `Python 2.7.15+`

In both environments I have `Pillow==6.1.0`

Is there any way around it?

**Comment by JohannesBuchner** [comment]
The error indicates that this is not a imagehash issue, but pip tries to install the latest numpy version.

Install an older version of numpy. Likely your package manager has a suitable one.

**Comment by k0fi** [comment]
Well, I installed `numpy==1.16.4` on my legacy machine (the same version that I found working on my other `python2.7` machine which runs ImageHash fine. 
However I still get the same error:

```
pip install ImageHash
Downloading/unpacking ImageHash
  Downloading ImageHash-4.0-py2.py3-none-any.whl (295kB): 295kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/k0fi/.env/lib/python2.7/site-packages (from ImageHash)
Downloading/unpacking pywavelets (from ImageHash)
  Downloading PyWavelets-1.0.3.tar.gz (4.6MB): 4.6MB downloaded
  Running setup.py (path:/tmp/pip-build-l2fAsd/pywavelets/setup.py) egg_info for package pywavelets
    /tmp/pip-build-l2fAsd/pywavelets/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      from setuptools import setup, Extension
    warning: no files found matching 'pyproject.toml'
    warning: no files found matching '*.txt'
    warning: no files found matching 'cythonize.dat'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*.egg' found anywhere in distribution
    warning: no previously-included files matching '*.egg-info' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): pillow in /home/k0fi/.env/lib/python2.7/site-packages (from ImageHash)
Downloading/unpacking scipy (from ImageHash)
  Downloading scipy-1.3.1.tar.gz (23.6MB): 23.6MB downloaded
  Running setup.py (path:/tmp/pip-build-l2fAsd/scipy/setup.py) egg_info for package scipy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-l2fAsd/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-l2fAsd/scipy/setup.py", line 31, in <module>

    raise RuntimeError("Python version >= 3.5 required.")

RuntimeError: Python version >= 3.5 required.
```

Then I tried to install scipy as per my other machine:

`pip install scipy==1.2.2`

But got this:

`$ pip install scipy==1.2.2
Downloading/unpacking scipy==1.2.2
  Downloading scipy-1.2.2.tar.gz (23.1MB): 23.1MB downloaded
  Running setup.py (path:/tmp/pip-build-Ttt77U/scipy/setup.py) egg_info for package scipy
    /tmp/pip-build-Ttt77U/scipy/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      but powerful enough to be depended upon by some of the world's
    warning: no previously-included files matching '*_subr_*.f' found under directory 'scipy/linalg/src/id_dist/src'
    no previously-included directories found matching 'benchmarks/env'
    no previously-included directories found matching 'benchmarks/results'
    no previously-included directories found matching 'benchmarks/html'
    no previously-included directories found matching 'benchmarks/scipy'
    no previously-included directories found matching 'scipy/special/tests/data/boost'
    no previously-included directories found matching 'scipy/special/tests/data/gsl'
    no previously-included directories found matching 'scipy/special/tests/data/local'
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
Installing collected packages: scipy
  Running setup.py install for scipy
    Running from scipy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /home/k0fi/.env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    /home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    /home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 492, in <module>
        setup_package()
      File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 488, in setup_package
        setup(**metadata)
      File "/home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 395, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    Complete output from command /home/k0fi/.env/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ttt77U/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EJU4MQ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/k0fi/.env/include/site/python2.7:
    Running from scipy source directory.



Note: if you need reliable uninstall behavior, then install

with pip instead of using `setup.py install`:



  - `pip install .`       (from a git repo or downloaded source

                           release)

  - `pip install scipy`   (last SciPy release on PyPI)





lapack_opt_info:

lapack_mkl_info:

customize UnixCCompiler

  libraries mkl_rt not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']

  NOT AVAILABLE



openblas_lapack_info:

customize UnixCCompiler

customize UnixCCompiler

  libraries openblas not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']

  NOT AVAILABLE



openblas_clapack_info:

customize UnixCCompiler

customize UnixCCompiler

  libraries openblas,lapack not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']

  NOT AVAILABLE



atlas_3_10_threads_info:

Setting PTATLAS=ATLAS

customize UnixCCompiler

  libraries lapack_atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries tatlas,tatlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries tatlas,tatlas not found in /usr/local/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib

customize UnixCCompiler

  libraries tatlas,tatlas not found in /usr/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu

customize UnixCCompiler

  libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu

<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

  NOT AVAILABLE



atlas_3_10_info:

customize UnixCCompiler

  libraries lapack_atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries satlas,satlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries satlas,satlas not found in /usr/local/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib

customize UnixCCompiler

  libraries satlas,satlas not found in /usr/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu

customize UnixCCompiler

  libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu

<class 'numpy.distutils.system_info.atlas_3_10_info'>

  NOT AVAILABLE



atlas_threads_info:

Setting PTATLAS=ATLAS

customize UnixCCompiler

  libraries lapack_atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries ptf77blas,ptcblas,atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib

customize UnixCCompiler

  libraries ptf77blas,ptcblas,atlas not found in /usr/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu

customize UnixCCompiler

  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu

<class 'numpy.distutils.system_info.atlas_threads_info'>

  NOT AVAILABLE



atlas_info:

customize UnixCCompiler

  libraries lapack_atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries f77blas,cblas,atlas not found in /home/k0fi/.env/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries f77blas,cblas,atlas not found in /usr/local/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib

customize UnixCCompiler

  libraries f77blas,cblas,atlas not found in /usr/lib

customize UnixCCompiler

  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu

customize UnixCCompiler

  libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu

<class 'numpy.distutils.system_info.atlas_info'>

  NOT AVAILABLE



accelerate_info:

  NOT AVAILABLE



/home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [atlas]) or by setting

    the ATLAS environment variable.

  self.calc_info()

lapack_info:

customize UnixCCompiler

  libraries lapack not found in ['/home/k0fi/.env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']

  NOT AVAILABLE



/home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [lapack]) or by setting

    the LAPACK environment variable.

  self.calc_info()

lapack_src_info:

  NOT AVAILABLE



/home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [lapack_src]) or by setting

    the LAPACK_SRC environment variable.

  self.calc_info()

  NOT AVAILABLE



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 492, in <module>

    setup_package()

  File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 488, in setup_package

    setup(**metadata)

  File "/home/k0fi/.env/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 137, in setup

    config = configuration()

  File "/tmp/pip-build-Ttt77U/scipy/setup.py", line 395, in configuration

    raise NotFoundError(msg)

numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.

----------------------------------------
Cleaning up...`

So I given up.

**Comment by JohannesBuchner** [comment]
Again, install the required packages (numpy, scipy) with your linux package manager.

**Comment by k0fi** [comment]
Johannes, as I shown above, when I try to install the same version of `scipy` which works fine on my other python2.7 environment, I get such an untraceable mess of `NOT AVAILABLE` errors.

**Comment by JohannesBuchner** [comment]
I only see you trying with pip, not the Linux package manager. What linux distribution do you use?

**Comment by k0fi** [comment]
Yes I tried only pip because ImageHash is supposed to run inside that environment so why need to install packages globally? 
The machine on which ImageHash installed seamlessly is Ubuntu 18.08, and the one with which I have trouble installing is Debian 9.
