### ISSUE TITLE
Really Following Hacker Factor?

### ISSUE THREAD

**Issue by danshev** [JohannesBuchner/imagehash#97]
I'm trying to reconcile the Hacker Factor approach to pHash and the code in this library.  I'm copy / pasting the HF steps and intermixing the code from the `phash` function from here: https://github.com/JohannesBuchner/imagehash/blob/master/imagehash/__init__.py#L151

**_Is this library a different implementation of pHash?_**

**1a. Reduce size**. Like Average Hash, pHash starts with a small image. However, the image is larger than 8x8; 32x32 is a good size. This is really done to simplify the DCT computation and not because it is needed to reduce the high frequencies.

**1b. Reduce color.** The image is reduced to a grayscale just to further simplify the number of computations.

```python
image = image.convert("L").resize((img_size, img_size), Image.ANTIALIAS)
```

**2. Compute the DCT.** The DCT separates the image into a collection of frequencies and scalars. While JPEG uses an 8x8 DCT, this algorithm uses a 32x32 DCT.

```
pixels = numpy.asarray(image)
dct = scipy.fftpack.dct(scipy.fftpack.dct(pixels, axis=0), axis=1)
```
_My note: Here, it seems like there's an initial DCT and then another one, performed on the result of the first?_

**3. Reduce the DCT.** While the DCT is 32x32, just keep the top-left 8x8. Those represent the lowest frequencies in the picture.

```python
dctlowfreq = dct[:hash_size, :hash_size] # where hash_size was previously set to 8
```

**4. Compute the average value.** Like the Average Hash, compute the mean DCT value (using only the 8x8 DCT low-frequency values and excluding the first term since the DC coefficient can be significantly different from the other values and will throw off the average). Thanks to David Starkweather for the added information about pHash. He wrote: "the dct hash is based on the low 2D DCT coefficients starting at the second from lowest, leaving out the first DC term. This excludes completely flat image information (i.e. solid colors) from being included in the hash description."

```python
med = numpy.median(dctlowfreq)
```
_My note: Here, the median (not the average) is taken? And the first item is **not** excluded?_

**5. Further reduce the DCT.** This is the magic step. Set the 64 hash bits to 0 or 1 depending on whether each of the 64 DCT values is above or below the **average value**. The result doesn't tell us the actual low frequencies; it just tells us the very-rough relative scale of the frequencies to the mean. The result will not vary as long as the overall structure of the image remains the same; this can survive gamma and color histogram adjustments without a problem.

```python
diff = dctlowfreq > med
```

**6. Construct the hash.** Set the 64 bits into a 64-bit integer. The order does not matter, just as long as you are consistent. To see what this fingerprint looks like, simply set the values (this uses +255 and -255 based on whether the bits are 1 or 0) and convert from the 32x32 DCT (with zeros for the high frequencies) back into the 32x32 image:

**Comment by JohannesBuchner** [comment]
I think the `phash_simple` function followed the original algorithm more closely. This changed with the commits closing issues #13 and #17.
