### ISSUE TITLE
Add support of images that are already as numpy array

### ISSUE THREAD

**Issue by VasylVaskivskyi** [JohannesBuchner/imagehash#99]
It would be good a feature to be able to use images that are already loaded in python and represented as numpy matrix. 
From what I've seen, currently it is only possible to use images loaded using PIL.

**Comment by JohannesBuchner** [comment]
It seems like you can use Image.fromarray(pix), or, if you want to replace a image data, pic.putdata(pix). https://stackoverflow.com/questions/384759/how-to-convert-a-pil-image-into-a-numpy-array

**Comment by VasylVaskivskyi** [comment]
Well, you are right I can convert them manually. However, I've noticed that you convert PIL images to numpy arrays before processing, so maybe it would be easier to allow functions to accept two types of data.

**Comment by JohannesBuchner** [comment]
In principle it is possible to support this. However, it is ambiguous in what color space the numpy data would live in. This is necessary to know when computing luminescence, for example. PIL images carry this information, and I think they are not much more heavy than numpy-array+colorspace.

**Comment by JohannesBuchner** [comment]
Please reopen if you still have issues.
